import {p,note,list,table,worksheet,page} from './schema.mjs';
const finish=(title,fields,sources)=>page(title,'Turn the research into a documented decision.',[
p('Save the dated documents supporting your decision with the transaction file. Write down who confirmed each open issue and when the answer is due. If the answer affects affordability, financing, insurability, legal use, or resale, resolve it while your contract still gives you the relevant choices. Your agent coordinates the process; the lender, insurer, association, government office, or closing professional confirms the fact within its role.'),
worksheet('Your decision record',fields),
list('Before removing a contingency',['Review the actual documents and written estimates, including exclusions and assumptions.','Separate recurring costs, immediate cash needs, and possible future liabilities.','Confirm unresolved items, the person responsible, and the contractual response deadline.','Ask whether a new fact changes your price, terms, financing, or decision to proceed.']),
note('A useful question for every professional','What would make this estimate or approval change before closing, and what evidence would tell us that has happened?')],sources);
export const guides=[
{slug:'florida-property-tax-after-purchase',category:'Coastal ownership',audience:'civilian',shortTitle:'Florida property taxes',title:'The tax bill after you buy.',subtitle:'Understand reassessment, homestead, portability, and escrow before choosing your Florida home.',answer:'A seller’s Florida property-tax bill can substantially understate a new buyer’s future bill. A qualifying ownership change generally resets the assessment to just value the following January 1, so build your budget using the buyer’s expected assessment and exemptions.',pages:[
page('Why the seller’s bill can mislead','The purchase changes the owner and may change the tax calculation.',[
p('A long-term owner may have accumulated a large Save Our Homes assessment difference. That protection generally does not transfer to an unrelated buyer simply because it appears in the listing’s tax history. The property appraiser determines the assessment; a sale price is relevant evidence, but it is not a promise that the tax assessment will equal that exact price.'),
table('Four values to keep separate',['Term','Meaning for your budget'],[['Purchase price','What you agree to pay for the property'],['Just value','The property appraiser’s market-value determination'],['Assessed value','Value after applicable assessment limits or portability'],['Taxable value','Assessed value after applicable exemptions; can differ by taxing authority']]),
note('The reset rule has exceptions','Florida lists certain transfers between spouses, some transfers upon death, corrections of title, and other qualifying changes that may avoid reassessment. Ask the property appraiser and closing professional about your actual ownership structure.'),
worksheet('Bring these records',['Parcel number / county / taxing district:','Seller’s just, assessed, and taxable values:','Buyer estimate requested from / date:'])],['flSOH','flTax']),
page('Build a buyer estimate','Calculate the change before it becomes an escrow surprise.',[
p('Ask for a purchase-based estimate using your intended occupancy, expected exemption eligibility, and any documented portability. Identify which millage rates apply to which taxable values. Include non-ad valorem assessments such as charges appearing separately on the tax bill. A broad county percentage is less useful than the correct parcel, taxing district, and buyer circumstances.'),
table('Teaching example, not a parcel estimate',['Assumption','Annual amount'],[['Hypothetical school taxable value $400,000 × 6 mills','$2,400'],['Hypothetical other taxable value $375,000 × 10 mills','$3,750'],['Hypothetical non-ad valorem charges','$300'],['Illustrative annual tax / monthly reserve','$6,450 / $537.50']],'One mill is $1 per $1,000 of taxable value. The values and millages above are invented to teach the calculation; they are not current local rates or standard exemption amounts.'),
p('If a seller’s historical bill were $3,000 while your buyer estimate were $6,450, the annual difference would be $3,450, or $287.50 per month. A lender collecting only the old amount could later need to increase the payment and address a shortage. Ask the lender which assessment it used and whether the initial escrow matches the buyer estimate.'),
note('Compare the right years','Closing-year prorations and next-year ownership costs answer different questions. A credit at closing does not guarantee that your next full-year bill will match the seller’s bill.')],['flTax','flSOH']),
page('Homestead is an application','Eligibility belongs to the owner and the facts of residency.',[
p('Discuss January 1 ownership and permanent-residency requirements with the county property appraiser. The ordinary filing deadline is March 1; ask the office about any applicable late-filing process rather than assuming an exception applies. A primary-home mortgage designation does not itself file a Florida property-tax exemption.'),
list('Prepare for the property appraiser',['Verify the deed and parcel information after recording.','Collect the identity and residency evidence requested by your county.','Disclose any other residence-based property-tax benefit you or relevant household members claim.','Ask about portability, surviving-spouse, disability, military, or other exemptions when applicable.','Retain the submitted application, supporting documents, receipt, and approval.']),
note('Use the current exemption calculation','Florida’s additional homestead exemption has an inflation adjustment and does not apply identically to school and non-school taxes. Use the current county/DOR calculation; a flat “subtract $50,000 everywhere” shortcut can be wrong.'),
worksheet('Your application calendar',['January 1 eligibility confirmed with:','Application deadline / submission confirmation:','Other exemptions or portability to evaluate:'])],['flTax','flSOH']),
page('Portability is separate from the cap','An existing Florida benefit may help, but the calculation matters.',[
p('Save Our Homes limits annual assessed-value increases on qualifying homesteads after the initial year to the lower of 3% or the change in CPI. It does not cap the total tax bill at 3%: millage, assessments, exemptions, and other circumstances can change. The accumulated difference is an assessment benefit, not a cash credit.'),
p('A move from a prior Florida homestead may allow portability of all or part of that assessment difference. DOR says the new homestead must be established within three years of January 1 of the year the previous homestead was abandoned. That is not simply three years after the closing date. File the required transfer application with the new homestead application and obtain the county’s calculation.'),
table('Questions that change the answer',['Question','Who confirms it'],[['Was the old property a qualifying Florida homestead?','Previous county property appraiser'],['When was the old homestead abandoned?','Property appraiser using your circumstances'],['How much benefit transfers to this new property?','New county property appraiser'],['Does ownership or a move by one owner affect the share?','Property appraiser and closing/tax adviser']]),
note('Do not budget a benefit twice','Portability affects assessed value. Homestead exemptions affect taxable value. Ask for a worksheet showing each step rather than subtracting the same benefit twice.')],['flSOH']),
finish('Your tax and escrow checklist',['Buyer-based annual tax estimate / assumptions:','Monthly tax reserve / lender escrow amount:','Homestead / portability application status:','Next assessment notice review date:'],['flTax','flSOH'])]},
{slug:'alabama-florida-ownership-costs',category:'Coastal ownership',audience:'civilian',shortTitle:'Two states, total cost',title:'Compare the whole cost.',subtitle:'A practical ownership-cost comparison for coastal Alabama and the Florida Panhandle.',answer:'Compare individual properties using financing, buyer-based taxes, insurance, flood coverage, association costs, maintenance, and intended use. A lower purchase price or tax bill alone does not establish which coastal home is less expensive to own.',pages:[
page('Start with the same assumptions','Make an honest comparison between two specific addresses.',[
p('Use the same down payment, loan term, quote date, household budget, and ownership horizon. Record whether each property is a primary residence, second home, or rental. Occupancy can affect lending, insurance, tax classification, homestead eligibility, and permitted use. A condominium, detached house, and leasehold property can have very different obligations even at the same price.'),
table('Normalize the comparison',['Input','What to record for each property'],[['Financing','Loan amount, rate/APR, points, term, mortgage insurance or funding fee'],['Property tax','Buyer assessment, exemptions, district and non-ad valorem charges'],['Insurance','Same coverage limits and deductible basis, plus flood/wind where needed'],['Association','Dues, included services, reserve funding and assessments'],['Property condition','Inspection-based immediate repairs and replacement planning'],['Use','Rental rules, lease terms, occupancy limits and permit requirements']]),
note('Avoid statewide shortcuts','Neither “Alabama is cheaper” nor “Florida has no state income tax” resolves the cost of owning a particular property. Personal income-tax treatment is a separate, household-specific conversation with a tax professional.')],['alTax','alCalc','flSOH','insurance']),
page('Taxes follow the parcel and use','Alabama and Florida do not use the same assessment framework.',[
p('Baldwin County explains that eligible owner-occupied residential property is assessed at 10% of value, while other classifications may be assessed at 20%. Confirm your actual classification and homestead eligibility with the Revenue Commission. Do not take 10% of the home price and treat that amount as the tax bill; the assessment is then used with applicable millage and exemptions.'),
p('For the Florida property, obtain a buyer-based estimate after any reassessment and approved exemptions. A protected seller assessment is not a reliable forecast. Compare official estimates for the same ownership year, including special or non-ad valorem charges.'),
table('Illustration of Alabama assessment mechanics',['Hypothetical input','Calculation'],[['Appraised value','$400,000'],['Eligible Class III assessment at 10%','$40,000 assessed value'],['Illustrative 40 mills before exemptions','$40,000 × .040 = $1,600'],['If classification were 20% at the same illustrative mills','$80,000 × .040 = $3,200']],'40 mills is an invented teaching assumption, not a quoted Gulf Shores, Orange Beach, or Baldwin County rate. Actual districts, exemptions, classifications and charges control.'),
note('Use the official calculator correctly','Select the actual location and use assumptions in Baldwin County’s calculator, then confirm the result with the Revenue Commission. Save the dated output with your property comparison.')],['alTax','alCalc','flSOH']),
page('A lower price can have a higher payment','This example illustrates the comparison method, not current local costs.',[
table('Two hypothetical homes, monthly planning budget',['Cost','Home A','Home B'],[['Principal and interest','$2,350','$2,200'],['Buyer-based property tax','$500','$280'],['Homeowners / wind coverage','$300','$475'],['Flood coverage','$90','$140'],['HOA / condominium dues','$75','$450'],['Maintenance reserve','$250','$150'],['Utilities estimate','$225','$225'],['Total monthly planning cost','$3,790','$3,920']]),
p('Home B has $150 less principal and interest and $220 less estimated tax, but the complete budget is $130 higher each month. Over 36 months that difference is $4,680 before cost changes. These are invented properties, not representative state averages. The point is to use actual comparable quotes and avoid letting one attractive number hide another obligation.'),
note('Separate budget from lender qualification','A lender may qualify using a housing expense definition that does not include your full maintenance, utilities, travel, or future-assessment reserve. Your household decision should include those costs.'),
worksheet('Your comparable quotes',['Property A / Property B / quote dates:','Coverage differences or unpriced obligations:','Monthly difference / cash needed at closing:'])],['alCalc','insurance','flood']),
page('The costs that arrive later','Model the exit as carefully as the purchase.',[
list('Stress-test both properties',['A new roof, HVAC replacement, water intrusion, or other item identified by inspection.','Higher renewal insurance premiums and the cash needed for the applicable storm deductible.','Association assessments, reserve increases, building repairs, or master-policy deductibles.','A vacancy or reduced rent if your intended use is legally permitted rental use.','Selling costs, mortgage payoff, and repairs if your ownership period is shorter than planned.']),
p('Ask a property manager for a written, address-specific operating analysis if rental use is part of the decision. Distinguish gross booked revenue from net proceeds after vacancy, fees, cleaning, utilities, taxes, insurance, repairs, and management. Confirm city, county, association, and lease restrictions separately. A platform listing or seller’s historical income does not establish your future right to rent.'),
table('Cash reserve worksheet',['Reserve purpose','How to estimate'],[['Immediate work','Inspection and specialist quotes'],['Storm deductible','Actual policy declarations and deductible basis'],['Operating cushion','Your chosen months of essential expenses'],['Exit or temporary vacancy','Written selling/rental plan and conservative assumptions']]),
note('No guaranteed appreciation assumption','A sound decision should survive a period of flat value and higher costs. Test a downside scenario instead of assuming appreciation will cover every expense.')],['insurance','flood','condo']),
finish('Your two-property decision',['Property addresses / intended use:','Confirmed tax and insurance estimates:','Monthly cost / initial cash / reserve difference:','Unresolved restriction or repair / owner / deadline:'],['alTax','alCalc','flSOH'])]},
{slug:'pensacola-beach-leasehold-due-diligence',category:'Coastal ownership',audience:'civilian',shortTitle:'Pensacola Beach leaseholds',title:'Know the lease beneath the home.',subtitle:'A document-first due-diligence guide for a Pensacola Beach leasehold purchase.',answer:'For a Pensacola Beach leasehold purchase, review the actual lease, amendments, assignment requirements, fees, remaining term, permitted uses, financing, and title coverage before committing. A listing description cannot establish the rights and obligations conveyed by the transaction.',pages:[
page('Understand the interest you are buying','The building, land rights, and contract obligations need separate review.',[
p('Many Pensacola Beach transactions involve leasehold rights administered through the Santa Rosa Island Authority. Confirm the legal interest for the exact parcel and improvements with the title company or closing attorney. Do not assume every beach-area property has identical terms, fees, renewal provisions, or ownership structure.'),
table('Request the complete file',['Document','Why it matters'],[['Recorded lease and all amendments','Defines the rights, term and obligations'],['Legal description and title commitment','Identifies what is conveyed and exceptions'],['Assignment requirements and approvals','Establishes the transfer process'],['Current fee and account statement','Shows amounts due and any arrears'],['Survey and available permits','Helps identify boundaries, improvements and approved work'],['Association documents if applicable','Adds a separate layer of use and financial obligations']]),
note('Two questions before touring seriously','Has the lender reviewed this leasehold structure, and has the closing professional identified every approval needed to convey it? Early answers prevent a late financing or transfer surprise.')],['lease','sria']),
page('Read the lease as an operating agreement','The most important terms may be in an amendment.',[
list('Ask the closing professional to explain',['The remaining lease term, renewal language, conditions, and whether a renewal is automatic or requires action.','Fees, adjustments, reassessments, payment dates, and consequences of default.','Assignment, sublease, lender, and transfer-consent requirements.','Permitted residential or other use, improvements, reconstruction and approval provisions.','Casualty, condemnation, termination, and insurance provisions.','Any outstanding violation, consent, lien, or required corrective work.']),
p('A long remaining term does not answer whether a particular lender will finance the property. A seller’s previous loan does not prove that your lender or loan program will accept the same lease today. Provide the complete lease package to underwriting early and get the property eligibility question resolved within your contract deadlines.'),
table('Put answers in writing',['Issue','Evidence to retain'],[['Current fees and balance','SRIA/account statement with effective date'],['Transfer requirements','Current SRIA forms and closing checklist'],['Intended rental or renovation','Applicable written approvals and restrictions'],['Financing','Lender’s review of the specific lease and title requirements']])],['lease','sria']),
page('Price the complete obligation','Lease-related charges are additional inputs in the ownership budget.',[
table('Hypothetical monthly worksheet',['Expense','Example'],[['Principal and interest','$2,500'],['Property taxes','$550'],['Homeowners / wind','$400'],['Flood','$125'],['Lease-related annual charge $1,800 ÷ 12','$150'],['Association / maintenance reserve','$425'],['Total excluding utilities','$4,150']],'Every amount is hypothetical, including the lease charge. Obtain the actual SRIA/lease account amount, current taxes and property-specific insurance quotes.'),
p('A $1,800 annual lease charge costs $150 per month, but the cash may be due on a different schedule. Ask which charges your lender escrows and which you must pay directly. Include transfer costs and immediate repair requirements separately from recurring ownership costs.'),
note('Flood and wind are different exposures','Check the policy definitions, coverage and deductibles with the insurer. The structure’s location, elevation, construction and condition matter more than a blanket statement that a beach address is “covered.”'),
worksheet('Your actual budget',['Annual lease-related charges / effective date:','Buyer tax estimate / wind and flood quotes:','Transfer costs / outstanding obligations:'])],['lease','insurance','flood']),
page('Coordinate approvals before deadlines','A good closing file links the lease, lender, insurer and title company.',[
table('Transaction control points',['When','Action'],[['Before offer','Identify tenure, lease package, lender acceptance and intended-use questions'],['During review period','Analyze lease/title, inspect, price insurance, request authority information'],['Before financing approval','Resolve leasehold underwriting and title conditions'],['Before signing','Confirm assignment/consent process, fee status and required documents'],['At closing','Verify what is conveyed, recorded and delivered'],['After closing','Retain recorded documents and calendar direct-pay obligations']]),
p('Treat short-term rental plans, substantial renovation, rebuilding after casualty, and transfer into an entity as separate questions. Prior practice or an online rental listing is not written authorization. Ask the proper authority and legal adviser which approvals apply to your proposal and whether the answer changes under current rules.'),
note('A low price does not resolve a document gap','An unclear lease amendment, unresolved title exception, or missing consent needs an answer. Price negotiation and legal confirmation perform different jobs.')],['lease','sria']),
finish('Your leasehold review record',['Lease / amendments received and reviewed by:','Remaining term / fees / renewal provisions:','Assignment and lender conditions:','Permitted use / unresolved approval / deadline:'],['lease','sria'])]},
{slug:'gulf-coast-condo-due-diligence',category:'Coastal ownership',audience:'civilian',shortTitle:'Condo due diligence',title:'Buy the building, too.',subtitle:'A financial, structural, insurance, and use review for a Gulf Coast condominium.',answer:'A condominium purchase includes exposure to the association’s finances, building condition, insurance, restrictions, and future projects. Review those records alongside the unit inspection and lender approval, because attractive interiors and low dues cannot establish the building’s financial health.',pages:[
page('Begin with the building file','A unit inspection and association review answer different questions.',[
table('Request before your review period expires',['Record','What you want to learn'],[['Current budget and financial statements','Revenue, expenses, collections and reserves'],['Recent board and owner meeting minutes','Discussed projects, disputes and future spending'],['Reserve studies and structural reports','Recommended work, timing and funding'],['Special assessment notices','Amounts, installments, purpose and allocation'],['Master insurance and deductibles','Coverage, exclusions, limits and owner exposure'],['Declaration, rules and amendments','Use, rental, pets, parking and approval restrictions'],['Litigation and lender questionnaire','Known legal and financing issues']]),
p('Ask what is missing and when it will arrive. An incomplete package is not the same as a clean package. The lender’s condominium review may evaluate project eligibility and insurance even when your personal credit and income are approved.'),
note('Florida and Alabama rules differ','Florida’s milestone inspection and structural integrity reserve study framework is state-specific. Do not apply a Florida deadline or requirement automatically to an Alabama building.')],['condo','condoFAQ']),
page('Separate inspection from funding','A building can have a report and still lack a workable financial plan.',[
p('In Florida, milestone inspections and structural integrity reserve studies serve different purposes. Applicability and timing depend on the building and current law, including amendments and exceptions. Obtain the actual dated reports and the association’s written explanation of applicable requirements. Confirm compliance status with the appropriate authority rather than relying on a generic calendar from an older article.'),
list('Questions for the association and specialists',['What work is recommended, required, completed, deferred, or still being investigated?','Has a qualified professional priced the scope, and how current are the bids?','Will reserves, additional dues, assessments, borrowing, insurance proceeds, or a combination fund the work?','What access restrictions or disruption should an owner expect?','Are there unresolved permit, inspection, engineering, or contractor issues?','What documents will the lender need before project approval?']),
note('A reserve balance alone is not a verdict','A large account balance may be inadequate for larger obligations; a small balance may follow recently completed, paid work. Compare the balance with the study, component condition, schedule and funding plan.')],['condo','condoFAQ']),
page('Translate an assessment into your cash plan','Ask who owes it, when, and under which agreement.',[
table('Hypothetical assessment scenario',['Input','Result'],[['Illustrative association project','$2,400,000'],['Equal allocation among 80 units','$30,000 per unit'],['If paid over 24 equal installments','$1,250 per month'],['Plus existing monthly dues of $650','$1,900 per month before mortgage/tax/unit insurance']],'Equal allocation is only a teaching assumption. Actual ownership shares, declarations, assessment resolutions, financing terms and the purchase contract control.'),
p('Ask whether the assessment is adopted, proposed, due now, payable in installments, or tied to future costs. Your purchase contract must address buyer/seller responsibility. A seller paying an existing assessment does not guarantee there will be no later assessment for another project or an overrun.'),
worksheet('Assessment register',['Resolution / project / total association amount:','Unit allocation / due dates / remaining balance:','Buyer/seller allocation in signed contract:','Potential additional work or cost not included:']),
note('Do not hide the installment in the dues line','Show regular dues, existing assessment payments, and your reserve for uncertain costs separately. This makes comparisons between buildings more useful.')],['condoFAQ']),
page('Match the policies and your intended use','A master policy is not a substitute for reviewing unit-owner coverage.',[
p('Provide the association’s insurance documents to your insurance professional and lender. Ask where the master policy’s responsibility ends and yours begins. Review unit improvements, contents, liability, loss assessment, water-related exclusions, additional living expenses and applicable deductibles. Standard homeowners and condo coverage generally excludes flood; discuss separate coverage and any building-level policy.'),
list('Confirm these before relying on a rental plan',['Minimum rental term, annual rental limits, approval process and waiting periods.','City/county licensing, registration, tax and safety requirements for your intended use.','Rules for guests, parking, pets, access, amenities and management arrangements.','Whether lender and insurance occupancy descriptions match actual planned use.','Gross revenue versus net operating income after every expense and vacancy.']),
note('A different buyer may need different financing','Ask whether the project is eligible for your actual loan program. A cash sale in the building or another buyer’s approval is not evidence that your loan will close.')],['insurance','flood','condoFAQ']),
finish('Your condominium decision file',['Reports received / reviewer / unresolved findings:','Dues / assessments / reserves / projected work:','Master and unit coverage gaps / lender approval:','Use restrictions / contract review deadline:'],['condo','condoFAQ','insurance'])]},
{slug:'coastal-insurance-and-flood',category:'Coastal ownership',audience:'civilian',shortTitle:'Insurance and flood',title:'Know what the policy will pay.',subtitle:'A Gulf Coast buyer’s guide to coverage, deductibles, flood, and insurance timing.',answer:'Obtain property-specific insurance quotes early, then compare coverage, exclusions, deductibles, and effective dates as carefully as premiums. Wind damage, flood, and water-related losses can fall under different rules or policies, and a lender’s minimum requirement may not match your risk tolerance.',pages:[
page('Quote the actual property early','The annual premium is the beginning of the review.',[
list('Prepare a useful quote request',['Exact address, intended occupancy and any planned rental use.','Construction, roof age and materials, available permits and repair records.','Existing inspection reports, wind-mitigation information and any elevation information.','Prior claims or damage information requested by the insurer.','Desired effective date and lender requirements.','Replacement-cost assumptions, contents, liability and additional living expenses.']),
p('Ask which inspection, repair, roof, electrical, plumbing or other condition could prevent binding coverage or cause a change after inspection. Quote approval is not always the same as a bound policy. Share material property or use changes promptly and obtain the written effective date before closing.'),
table('Three separate confirmations',['Item','Written evidence'],[['Premium estimate','Quote with assumptions and expiration'],['Coverage commitment','Binder or other insurer confirmation'],['Final coverage','Declarations, policy and endorsements']])],['insurance']),
page('Translate a percentage deductible','The percentage may apply to insured value, not the claim.',[
p('Florida’s hurricane deductible guidance explains that the deductible can be expressed as a percentage of the policy’s dwelling coverage. Read your actual declarations and policy language. A percentage that sounds small can create a significant cash obligation after a storm.'),
table('Hypothetical $400,000 dwelling coverage',['Deductible assumption','Potential deductible amount'],[['2% of dwelling coverage','$8,000'],['5% of dwelling coverage','$20,000'],['Difference in cash exposure','$12,000']],'These are teaching calculations, not a statement that each option is offered or appropriate for your property. Trigger, calendar-year rules, exclusions and other deductibles depend on applicable law and the policy.'),
list('Ask the insurer',['What event activates each deductible?','Does it apply per occurrence, per calendar year, or another way?','Which dollar amount is the percentage multiplied by?','Could wind, flood, or another cause create separate deductibles?','What cash reserve would cover the selected deductible without using retirement funds or high-cost debt?']),
note('A premium saving has a tradeoff','Compare the annual saving with the extra deductible exposure. Choosing a higher deductible should be a deliberate cash-reserve decision.')],['hurricane','insurance']),
page('Flood is a separate question','An address outside a high-risk mapped area can still flood.',[
p('Discuss flood risk and coverage even when a lender does not require a flood policy. Compare flood policy limits, building versus contents coverage, exclusions, replacement-cost versus actual-cash-value provisions, and the deductible. Ask how a condominium master flood policy interacts with unit-owner coverage.'),
p('NFIP policies typically have a 30-day waiting period, with specified exceptions, including qualifying coverage purchased in connection with making, increasing, extending, or renewing a loan. Do not assume an exception applies to a cash purchase or a policy change. Confirm the effective date in writing with the insurer. Private flood coverage may have different terms.'),
table('Flood review worksheet',['Question','Evidence'],[['What does the lender require?','Flood determination and loan conditions'],['What is the property’s exposure?','Current map, elevation information and property history'],['What does the policy cover?','Policy form, limits, exclusions and deductible'],['When does it begin?','Written effective date and waiting-period determination']]),
note('A map designation is one input','Surface drainage, local conditions, storm surge and intense rainfall can matter to the ownership decision. Ask appropriate professionals about the actual site rather than relying on a broad neighborhood label.')],['flood','insurance']),
page('Compare quotes line by line','A cheaper policy may insure a different risk.',[
table('Same-property comparison',['Feature','Quote A / Quote B notes'],[['Dwelling reconstruction amount','Same valuation assumptions?'],['Roof settlement and exclusions','Replacement cost, depreciation, limitation or exclusion?'],['Hurricane / wind / other deductible','Same trigger and dollar exposure?'],['Flood','Included, separate, or absent?'],['Loss of use / contents / liability','Same limits and exclusions?'],['Required repairs or inspections','Conditions and completion deadline?'],['Annual cost and payment plan','Fees, installments and escrow treatment?']]),
p('Do not select a policy only to satisfy the closing checklist. Keep the quote assumptions, inspection records, binder, declarations, endorsements and agent contact together. Revisit coverage after a renovation, occupancy change, new rental use, or major replacement. A renewal review should compare the new terms, not just the premium.'),
note('Protect the transaction calendar','A storm, binding restriction, inspection issue or missing documentation can affect coverage timing. Ask the insurance professional about the current situation before you waive protection or make an irreversible moving commitment.')],['insurance','hurricane','flood']),
finish('Your insurance readiness sheet',['Carrier / agent / quote expiration / effective date:','Annual premiums / escrow or direct payment:','Deductible amounts / reserve available:','Required repairs / exclusions / unresolved questions:'],['insurance','hurricane','flood'])]},
{slug:'inspection-to-repair-decision',category:'Buying',audience:'civilian',shortTitle:'Inspection decisions',title:'From inspection to a decision.',subtitle:'A practical system for evaluating condition, getting specialist answers, and negotiating repairs.',answer:'Use the inspection period to understand condition, obtain appropriate specialist opinions and cost estimates, and decide whether the property still fits your budget and contract. An inspection, appraisal, insurance inspection, and warranty each serve different purposes.',pages:[
page('Order the right reviews','Begin with your contract deadline and the property’s features.',[
p('Ask the inspector what the inspection includes, what it excludes, and what conditions could limit access. Roof, structural, electrical, plumbing, HVAC, moisture, drainage, pest, pool, septic, well, and other questions may require qualified specialists. Schedule the general inspection early enough to leave time for follow-up and a written contractual response.'),
table('Different reviews, different purposes',['Review','Useful question'],[['General home inspection','What visible and accessible condition issues require attention?'],['Specialist evaluation','What is the cause, scope, repair method and cost?'],['Appraisal','Does the property support the lender’s valuation and program requirements?'],['Insurance inspection','Does the property meet the insurer’s requirements?'],['Survey / title review','What boundaries, access, rights and exceptions affect ownership?']]),
note('No report guarantees a defect-free home','Read limitations, inaccessible areas and recommendations. A “not inspected” component is unresolved, not confirmed acceptable.')],['vaBuying','insurance']),
page('Sort findings by consequence','The most expensive item is not always the first priority.',[
table('An action-oriented triage',['Category','Next step'],[['Immediate safety concern','Ask a qualified professional for prompt evaluation'],['Active damage or water entry','Identify cause, extent, remediation and continuing risk'],['Financing or insurance condition','Confirm the lender/insurer requirement and timing'],['Near-term replacement','Obtain cost and expected planning horizon'],['Maintenance or cosmetic issue','Decide what you can accept and budget after closing']]),
p('Ask the inspector to explain which observations are material and which are routine maintenance. Avoid converting a report into a list of demands without understanding the cause or cost. Conversely, a short report is not proof of low risk if important areas could not be accessed.'),
worksheet('One row per material issue',['Issue / photo / report page:','Specialist / scope / written estimate:','Effect on safety, insurance, financing or use:','Decision deadline / responsible person:']),
note('Obtain permission before invasive work','Testing that opens walls, removes materials or changes the property needs the required consent and qualified handling. Coordinate access through the transaction professionals.')]),
page('Turn findings into realistic numbers','A credit is useful only if the transaction permits it and the work is manageable.',[
table('Hypothetical repair decision',['Item','Example'],[['Specialist repair estimate','$7,500'],['Buyer contingency allowance, chosen for this example','$1,500'],['Planning total','$9,000'],['Seller credit offered','$5,000'],['Remaining buyer budget if credit is usable','$4,000']],'An example credit does not establish lender eligibility or cash available for repairs. Loan limits on credits and actual closing costs can restrict the benefit.'),
p('A seller repair, price adjustment, closing-cost credit, or decision to accept the condition can produce different outcomes. Ask whether a credit is allowed, whether the lender requires the work before closing, and whether you have cash and time to complete it. A price reduction does not automatically put the same amount of cash in your repair account.'),
note('Define a repair precisely','Identify scope, required permits, contractor qualifications, completion date, invoices, warranties, and any reinspection. “Fix roof” is much less useful than a clear agreed scope based on a qualified evaluation.')]),
page('Close the loop before closing','A negotiated promise needs evidence of completion.',[
list('Confirm the repair file',['Signed agreement describing responsibilities and dates.','Invoices, permit or inspection records when required, and transferable warranties.','Photos or access for reinspection of material repairs.','Lender and insurer confirmation for their conditions.','A final walkthrough consistent with the contract.','A written solution for incomplete work through the appropriate professionals.']),
p('At the walkthrough, compare the property with the agreement and look for agreed repairs, included items, new damage, possession conditions and utilities needed for verification. It is not a substitute for the original inspection. Report discrepancies immediately so the closing professionals can address them before signing or funding as appropriate.'),
note('Do not rely on an informal escrow promise','Any holdback or post-closing repair arrangement needs approval from the necessary parties, including the lender when applicable, and clear written terms. Your agent and closing professional should coordinate it.')]),
finish('Your inspection decision record',['Material findings / accepted conditions:','Agreed repairs or credit / signed document:','Specialist evidence / lender / insurer clearance:','Walkthrough date / unresolved issue / next action:'],['insurance'])]}
];
