import {p,note,list,table,worksheet,page,payment,money} from './schema.mjs';
export const guides=[
{
 slug:'preapproval-first',category:'Start here',audience:'civilian',shortTitle:'Preapproval first',title:'Preapproval comes first.',subtitle:'What it means, what it does not mean, and how to start a home search with a usable budget.',
 answer:'A preapproval is a lender’s conditional assessment of your ability to borrow. Make a lender conversation and a comfortable payment budget your first two steps, before serious home shopping or an offer.',
 pages:[
 page('What you are actually getting','The letter is useful evidence of preparation. The work behind it matters more than the label.',[
 p('A lender reviews information about your income, assets, debts, and credit, then indicates the amount it may be willing to lend under stated assumptions. The CFPB cautions that a preapproval is not a guaranteed loan offer. The property, updated documents, underwriting conditions, and final checks still matter.'),
 table('Ask what has been reviewed',['Stage','What to establish'],[['Initial conversation','A preliminary range based on information you share. Ask whether credit and documents were reviewed.'],['Document-supported preapproval','The lender has examined supporting information. Ask which income, assets, and debts were verified.'],['Underwritten approval, if offered','An underwriter has reviewed the borrower file, often subject to property and other conditions. Get the remaining conditions in writing.'],['Final approval / clear to close','The lender authorizes the next closing steps after conditions are met. Funding and possession still follow the closing process.']]),
 p('Lenders use “prequalification” and “preapproval” differently. Do not assume that two letters represent the same level of review. Ask who reviewed the file, what is missing, and whether the proposed property type changes the answer.'),
 note('A better question','Instead of asking only “How much am I approved for?”, ask “What monthly payment, cash to close, property assumptions, and conditions support this approval?”')
 ],['preapproval']),
 page('Your first two steps','Start with a real budget and a lender conversation. Their order can overlap.',[
 list('Step 1: Define what comfortable means',['Choose a monthly housing amount that leaves room for savings, childcare, transportation, travel, and irregular bills.','List the cash you can use for closing separately from the emergency reserve you want to keep.','Set your moving date, employment or PCS constraints, and any home-sale contingency.','Discuss your search and representation with your agent, including the services and compensation in your agreement.']),
 list('Step 2: Get the financing reviewed',['Contact lenders, explain your timing, and ask what level of preapproval they provide.','Use the lender’s secure portal for identity, income, asset, and credit documents.','Ask the lender to price realistic taxes, insurance, flood coverage, HOA dues, and mortgage insurance where applicable.','Confirm the letter’s expiration date, update requirements, and property limitations before touring seriously.']),
 p('Early review can surface a credit-report error, an undocumented deposit, variable-income treatment, or a required debt payoff while you still have options. Shopping first can leave those issues to be solved after an inspection clock and earnest-money deadline are already running.'),
 note('You choose the budget','A lender’s maximum is an eligibility result under its rules. Your spending target is a household decision. A higher approval does not require you to raise your target price.')
 ],['preapproval']),
 page('Build the document folder','This is a preparation list. Your lender provides the exact requirements and lookback periods.',[
 table('Common requests',['Category','Prepare or ask about'],[['Identity / application','Government identification, legal names, residential history, and authorization for credit review through the secure application.'],['Employment income','Recent pay statements, W-2s, employment history, and explanations for transitions or variable compensation.'],['Self-employment','Personal and business returns as requested, year-to-date profit and loss, balance sheet, and business account information.'],['Assets','Complete statements with all pages for funds used at closing; document transfers, gifts, and unusual deposits.'],['Existing obligations','Mortgages, vehicle/student loans, support obligations where applicable, and other recurring debts.'],['Military / VA, when applicable','COE, LES, orders, service documentation, and applicable benefit documentation through the lender.'],['Property / transaction','Executed contract once available, HOA information, property insurance quotes, and the existing-home sale details if relevant.']]),
 p('Upload complete statements rather than screenshots of an account balance. A balance alone does not explain account ownership or the source of money. Tell the lender before moving funds or relying on a gift. Ask which documents can be supplied later and which block the approval today.'),
 note('Keep sensitive documents in the right place','Do not email Social Security numbers, bank credentials, or full financial files to a general inquiry address. Use the lender’s verified secure channel.')
 ],['preapproval','documents']),
 page('Turn a price into a payment','A realistic ownership budget includes expenses outside the loan payment.',[
 table('Illustrative $350,000 loan, 30 years',['Assumed fixed rate','Monthly principal + interest'],[5.5,6,6.5,7].map(r=>[`${r.toFixed(1)}%`,money(payment(350000,r))]),'Calculated examples only. These are not current rate offers. Taxes, insurance, assessments, mortgage insurance, and other ownership costs are excluded.'),
 table('Build the actual monthly number',['Expense','Your monthly amount'],[['Principal + interest','Use a written lender scenario'],['Property taxes','Estimate after the purchase, not from the seller’s old bill'],['Homeowners / wind insurance','Annual quote divided by 12'],['Flood insurance','Separate quote when applicable'],['HOA / condominium charges','Include known special assessments separately'],['Maintenance + reserve','Choose a property-specific reserve, outside lender escrow']]),
 p('Compare homes using the same assumptions. A lower-priced coastal condo can carry higher association costs, and a seller’s tax bill can understate a buyer’s future bill. Ask the lender whether a changed insurance quote affects the approval amount.'),
 note('Cash to close is a separate calculation','Down payment plus closing costs, prepaid expenses, and initial escrow, less deposits and allowable credits, is different from the monthly payment.')
 ],['preapproval','cd']),
 page('Protect the approval','Treat material financial changes as questions to ask before you act.',[
 list('Tell the lender before you',['Change jobs, compensation structure, hours, or self-employment status.','Finance a car, furniture, appliances, or another major purchase.','Open or close credit accounts, co-sign, or take on a new payment.','Move large sums between accounts or accept a gift for closing.','Make a large debt payoff or cash deposit without a documented plan.','Change the purchase price, occupancy plan, property type, or source of funds.']),
 p('Continue paying obligations on time and answer document requests promptly. A preapproval can expire or need updating. The CFPB describes common letter periods of 30 to 60 days, but the date and terms on your lender’s actual letter control.'),
 table('Useful questions for your lender',['Question','Why it matters'],[['What could still prevent closing?','Separates borrower, property, and documentation conditions.'],['Is the rate locked? Until when?','A preapproval is not automatically a rate lock.'],['Can this approval support a condo or assumption?','Special property and product rules may apply.'],['When will you refresh the documents?','Helps avoid last-week surprises.']])
 ],['preapproval']),
 page('Your preapproval conversation sheet','Complete this with the lender and bring the agreed budget to your home search.',[
 worksheet('Record the working plan',['Comfortable total monthly housing payment:','Maximum cash for closing / reserve to keep:','Lender / loan officer / verified contact:','Loan type / down payment / assumed interest rate:','Taxes / insurance / HOA assumptions:','Documents reviewed / conditions still outstanding:','Preapproval expiration / rate-lock expiration if any:','Target purchase date / next action / person responsible:']),
 note('When the offer is accepted','Send the executed contract to the lender promptly. Obtain and compare formal Loan Estimates when the application requirements are met. A preapproval does not commit you to that lender.'),
 p('Bring the letter, the assumptions, and your payment target together. That gives your agent a useful search range and lets you make an offer with a clearer understanding of the financing work still ahead.')
 ],['preapproval','documents'])
 ]
},
{
 slug:'buyer-transaction-roadmap',category:'Buying',audience:'civilian',shortTitle:'The buyer transaction',title:'From first conversation to front-door keys.',subtitle:'A buyer’s transaction checklist, decision map, and working timeline.',
 answer:'Start with a comfortable payment budget and lender preapproval, then search, negotiate, inspect, finalize financing, and close. Your signed contract sets the deadlines; this guide shows what needs to happen at each stage.',
 pages:[
 page('The complete transaction at a glance','This sequence is a planning framework, not a promised closing duration.',[
 table('The sequence',['Stage','Your work','What moves the file forward'],[['1. Prepare','Budget, lender preapproval, agent consultation','Usable payment and cash-to-close plan'],['2. Search','Compare properties and ownership costs','A home that fits budget and objectives'],['3. Offer','Review price, contingencies, deposit, dates','Fully signed contract'],['4. Due diligence','Inspect, quote insurance, review title and association','Documented decisions before deadlines'],['5. Financing','Complete underwriting and appraisal conditions','Lender approval and closing preparation'],['6. Close','Review figures, verify funds, walk through, sign','Funding/recording and possession as agreed'],['7. Own','Service transfer, maintenance, tax planning','A documented ownership handoff']]),
 p('Preapproval belongs in the first or second step because financing affects every later decision: purchase price, property eligibility, inspection and appraisal timing, cash reserves, and what you can responsibly promise in an offer. A pleasant tour does not answer those questions.'),
 note('Make two calendars','Keep a transaction calendar with contractual deadlines and a household calendar with lease notice, moving, work, school, and temporary-lodging dates. A change in one can affect the other.')
 ],['preapproval','documents']),
 page('Before serious home shopping','Build the team and the numbers before the search becomes urgent.',[
 list('Your preparation checklist',['Discuss representation, services, compensation, and communication expectations with your agent.','Ask a lender for a documented preapproval; confirm what was reviewed and what remains conditional.','Set a payment target including taxes after purchase, insurance, flood coverage, HOA dues, and maintenance.','Keep closing cash and emergency reserves separate.','Write your needs: property type, work routes, accessibility features, outdoor space, and timing.','Identify lease, existing-home sale, employment, or PCS constraints.','Review properties by objective features and address-specific facts, not assumptions about who lives nearby.']),
 p('The lender, inspector, insurance professional, title company or closing attorney, association manager, and agent handle different questions. Decide how you will receive updates and where documents belong. Ask who can resolve each type of problem rather than expecting a single person to approve everything.'),
 worksheet('Your search brief',['Comfortable payment / available closing cash:','Target areas and routes to test:','Essential features / flexible preferences:','Move date / contingency / decision-makers:'])
 ],['preapproval']),
 page('Offer accepted: start the clocks','Calendar the actual signed terms immediately. Do not replace them with a generic checklist.',[
 table('Confirm in writing',['Item','What to record'],[['Effective date','The date used by the contract to calculate periods'],['Earnest money','Amount, holder, method, receipt, and exact due date'],['Inspection rights','Period, notice method, cancellation or repair provisions'],['Financing','Application, approval, and notification requirements'],['Appraisal','Any appraisal contingency or addendum and its limits'],['Title / survey / association','Delivery, review, objection, and approval deadlines'],['Closing / possession','Signing, funding, recording, keys, and any occupancy agreement']]),
 p('Get the executed contract to the lender and closing professional. Schedule inspections early enough to review results and obtain estimates before your decision deadline. Insurance quotes and association review should run alongside inspections rather than wait for underwriting to finish.'),
 note('Earnest money is not automatically refundable','The contract and your compliance with its notice and timing requirements determine the parties’ rights. Ask your agent or attorney before assuming an inspection issue or financing delay permits a refund.'),
 worksheet('First actions',['Deposit receipt confirmed by:','Inspection booked / decision deadline:','Lender and closing professional have the complete contract:'])
 ],['documents']),
 page('Investigate the property and its costs','An inspection, an appraisal, an insurance review, and a title review answer different questions.',[
 table('Four reviews',['Review','What you need to understand'],[['Inspection','Condition, safety concerns, systems, specialist follow-up, and repair priorities. It does not guarantee future performance.'],['Appraisal','The lender’s value and property-eligibility review. It is not your independent home inspection.'],['Insurance','Coverage availability, exclusions, roof eligibility, deductibles, wind/flood treatment, and the lender’s requirements.'],['Title / survey / association','Ownership, recorded restrictions, easements, boundaries, assessments, rental rules, and unresolved exceptions.']]),
 list('Turn findings into decisions',['Request specialist estimates when an issue materially affects your budget or willingness to buy.','Confirm permits and documentation for important alterations where relevant.','Review the insurance quote and required work with the lender before waiving protections.','Read association financials, insurance, inspection reports, and approved or proposed assessments.','Use your written contract to decide whether to accept, negotiate, or exercise a right before it expires.']),
 p('A seller credit cannot repair every problem. The lender may require certain repairs before funding, and a credit is constrained by the loan program and transaction. Ask whether the proposed solution is both contractually documented and financeable.')
 ],['vaBuying','condoFAQ']),
 page('The last stretch before closing','Protect the approval, confirm the numbers, and separate signing from possession.',[
 list('Financing and closing checklist',['Respond to underwriting requests with complete documents through the lender’s portal.','Confirm appraisal and insurance conditions are cleared and the rate lock covers the expected closing.','Review the Closing Disclosure and compare it with the latest Loan Estimate.','Ask about changes in loan amount, rate, cash to close, credits, prepaid items, and escrow.','Verify wire instructions using a trusted phone number obtained independently.','Complete the final walkthrough and check agreed repairs, included items, and the property’s condition.','Confirm identity requirements, remote-signing or power-of-attorney approval, and the possession agreement.']),
 p('For most covered mortgages, the lender must provide the Closing Disclosure at least three business days before consummation. The lender calculates that waiting period. Signing documents does not by itself mean funds have been disbursed or you are entitled to possession.'),
 note('Do not assume a last-minute fix is harmless','Certain loan changes require a corrected disclosure and a new waiting period. Ask the lender and closing professional whether a change affects the closing schedule before booking an irreversible move.')
 ],['disclosure','trid','cd']),
 page('After closing: make the handoff complete','A useful transaction ends with organized records and a plan for owning the property.',[
 table('Ownership handoff',['When to plan it','Action'],[['At possession','Confirm keys, remotes, access codes, utility transfer, warranties, and agreed personal property.'],['As documents arrive','Save the final signed package, settlement statement, title policy, survey, insurance declarations, and repair documentation.'],['Before first payment','Verify the servicer and payment instructions from trustworthy documents. Confirm when and where the first payment is due.'],['During the first month','Document maintenance priorities, replace filters as appropriate, and locate shutoffs.'],['Tax planning','Review homestead eligibility and filing dates with the county. The seller’s exemption does not transfer to you automatically.']]),
 worksheet('Your live deadline sheet',['Contract effective date / earnest-money due:','Inspection decision / finance approval due:','Insurance binding / association approval due:','Closing Disclosure receipt / lender-confirmed earliest closing:','Final walkthrough / closing / possession:','First mortgage payment / tax-exemption follow-up:']),
 p('Keep this sheet current when a written amendment changes a date. Assign an owner to each action so “someone is handling it” never becomes the reason a deadline is missed.')
 ],['documents','cd','flTax'])
 ]
},
{
 slug:'mortgage-preapproval-to-closing',category:'Financing',audience:'civilian',shortTitle:'The mortgage process',title:'The mortgage process, made clear.',subtitle:'From preapproval to funding: documents, responsibilities, timelines, and the questions to ask at every stage.',
 answer:'Mortgage approval progresses through borrower review, a property-specific application, processing, underwriting, disclosures, and funding. Complete documents and early questions reduce avoidable delays; the lender controls approval and loan timing.',
 pages:[
 page('The mortgage path','Know the difference between a planning milestone and a legal waiting period.',[
 table('An illustrative 30- to 45-day purchase schedule',['Planning window','Typical work in the file'],[['Before contract','Budget, credit and income review, preapproval, loan options'],['Contract days 1-3','Send contract, complete application, receive disclosure instructions'],['Days 3-10','Choose lender, process documents, order appraisal, obtain insurance'],['Days 7-25','Underwriting review and borrower/property conditions'],['Final week or longer','Resolve conditions, confirm rate lock, review closing figures'],['Required disclosure period','Receive Closing Disclosure at least three business days before consummation for covered loans'],['Closing / funding','Sign, satisfy lender funding requirements, disburse and record as applicable']],'The day ranges are illustrative workflow assumptions, not market averages, lender commitments, or contract deadlines. Some loans take substantially longer.'),
 p('Several steps run at the same time. Appraisal timing, insurance eligibility, a condominium project review, a job change, or a delayed home sale can affect the critical path. Ask which remaining item currently prevents closing and who owns the next action.'),
 note('Start before you have a contract','An early lender conversation gives you time to address documentation or credit issues without spending your inspection period on basic financing questions.')
 ],['preapproval','documents','disclosure']),
 page('Application and lender comparison','A preapproval letter and a Loan Estimate serve different purposes.',[
 p('For a covered mortgage, the six pieces of information that trigger the Loan Estimate requirement are your name, income, Social Security number to obtain a credit report, property address, estimated property value, and the mortgage amount sought. The creditor generally must deliver or mail the estimate within three business days after receiving those items. Required verification documents are a separate matter.'),
 table('Compare like with like',['Compare','Hold these assumptions consistent'],[['Loan structure','Product, term, fixed versus adjustable rate, loan amount, and down payment'],['Pricing','Interest rate, APR, points, lender credits, and lock period'],['Closing cash','Lender fees, third-party charges, prepaid items, escrow, and credits'],['Monthly cost','Principal/interest, mortgage insurance, tax and insurance assumptions'],['Execution','Communication, property eligibility, documentation, appraisal and closing expectations']]),
 p('Ask for estimates on the same property and similar dates, since pricing can change. A lender credit usually trades upfront cost against loan pricing. A lower cash-to-close figure is not automatically the less expensive loan over your expected ownership period.'),
 note('Rate-lock question','Ask whether the rate is locked, the expiration date, extension cost, float-down terms if offered, and what changes could invalidate the pricing. Keep the lock confirmation.')
 ],['trid','preapproval','cd']),
 page('Processing: turn documents into evidence','The file needs a traceable explanation of income, assets, debts, and the property.',[
 table('Your processing checklist',['Document stream','What commonly delays it'],[['Pay and employment','Missing pages, unexplained gaps, bonuses/commission history, or an upcoming job change'],['Self-employment','Incomplete returns, business cash-flow questions, and late profit-and-loss statements'],['Assets and gifts','Undocumented transfers, large deposits, gift-source questions, or inaccessible funds'],['Property','Incomplete contract/addenda, appraisal access, condo documents, title or survey issues'],['Insurance','Late quotes, roof questions, wind/flood requirements, or a binding restriction'],['Current home','Missing sale contract, payoff details, closing evidence, or lease documentation']]),
 list('Make every upload usable',['Include all pages and retain original document dates.','Use descriptive filenames and answer the exact request.','Ask whether an explanation requires supporting evidence or a signed statement.','Tell the loan officer if a requested document does not exist; agree on an acceptable alternative.','Keep one list of outstanding conditions, due dates, and responsible people.']),
 p('A condition request is not itself a denial. It identifies information or work needed to support the credit decision. Ask which items are required before approval, before documents, and before funding.')
 ],['preapproval','documents']),
 page('Underwriting, appraisal and insurance','Three independent reviews must work together.',[
 p('Underwriting evaluates the borrower and the loan against program and lender requirements. An appraisal supports the value and property review. Insurance must satisfy the lender’s coverage requirements and be available for the specific property. Approval in one area does not settle the others.'),
 table('If this happens…',['Situation','Productive next question'],[['Value below price','What does the contract allow, what value-review process exists, and what cash or renegotiation options are permitted?'],['Required property repair','Who completes it, who verifies it, and must it be done before funding?'],['Insurance quote increases','Does the revised payment still qualify, and can coverage be bound on time?'],['Condo project issue','Which project requirement is unmet, and what acceptable documentation or alternative product exists?'],['New debt or income change','Does the lender need to rerun the approval and update disclosures?']]),
 p('Do not waive a protection simply because someone says the issue is “probably fine.” Get the relevant professional’s answer and document any contract change. Financing and appraisal contingencies are not interchangeable.'),
 worksheet('Your condition tracker',['Condition / source of request:','Required evidence / responsible person:','Due date / confirmation of acceptance:'])
 ],['vaBuying','condoFAQ']),
 page('Disclosure, signing and funding','The final week should confirm the transaction you already understand.',[
 p('The Closing Disclosure states final loan terms, projected payments, transaction costs, and cash to close. For most covered purchase mortgages, you must receive it at least three business days before consummation. Ask your lender to confirm the applicable calendar; different disclosure rules use different definitions of business day.'),
 list('Review before signing',['Borrower names, address, purchase price, loan amount, term, rate, and payment.','Points, lender credits, seller credits, deposits already paid, and third-party charges.','Prepaid interest, tax/insurance escrows, assessments, and items paid outside closing.','Any balloon payment, prepayment penalty, adjustable-rate feature, or unusual term.','The amount and verified method for closing funds; never rely on changed email instructions alone.']),
 p('Under the CFPB’s TRID guidance, an inaccurate APR beyond the permitted tolerance, a loan-product change, or adding a prepayment penalty can trigger a new three-business-day waiting period after a corrected disclosure. Many other corrections do not, but the lender must make that determination.'),
 note('Keys follow the agreement','Ask what must happen after signing: lender funding authorization, disbursement, recording, and contractual possession. Do not promise a mover access based only on a signing appointment.')
 ],['disclosure','trid','cd']),
 page('Your mortgage control sheet','Keep the current version with the lender and closing professional.',[
 worksheet('Track the file',['Loan officer / processor / closing professional:','Loan type / amount / down payment / target payment:','Rate lock / expiration / extension terms:','Appraisal ordered / expected / accepted:','Insurance quote / binding date / remaining requirements:','Outstanding underwriting conditions / owners / dates:','Closing Disclosure received / lender-confirmed earliest consummation:','Signing / funding / possession / first-payment date:']),
 note('After closing','Keep the signed note, security instrument, settlement documents, and insurance evidence. Confirm the servicer’s identity before sending money. Continue reviewing tax and insurance escrow changes; a fixed interest rate does not freeze the entire housing payment.')
 ],['documents','cd'])
 ]
}
];
