import {p,note,list,table,worksheet,page,payment,money} from './schema.mjs';
const pi=(loan,rate,years=30)=>money(payment(loan,rate,years*12));
export const guides=[
{slug:'va-loan-insider-guide',category:'VA financing',audience:'military',shortTitle:'VA loan insider guide',title:'Your VA benefit, understood.',subtitle:'An insider’s field guide to entitlement, qualification, funding fees, payment math, and a well-prepared purchase.',answer:'A VA-backed purchase loan can offer eligible borrowers no required down payment and no monthly mortgage insurance, but eligibility, entitlement, lender approval, property requirements, and closing costs still matter. Compare the complete loan and household budget before deciding how to use the benefit.',pages:[
page('Start with eligibility and entitlement','A Certificate of Eligibility is one step in the financing decision.',[
p('Ask a VA-experienced lender to obtain or review your Certificate of Eligibility, or COE. Service requirements and eligibility categories differ for veterans, active-duty members, Guard/Reserve members and qualifying surviving spouses. The COE tells the lender about eligibility and entitlement; it does not approve your income, credit, property, or loan amount.'),
table('Three separate approvals',['Question','Evidence'],[['Are you eligible for the benefit?','COE and any required service records'],['Can you qualify for this loan?','Lender review of income, credit, debts, assets and occupancy'],['Does this property qualify?','Appraisal, condition, title, insurance and any project/lease review']]),
p('With full entitlement, VA does not set a loan limit that requires a down payment solely because the price exceeds a county limit. The lender still determines what you can afford and the property must meet requirements. With remaining entitlement, county loan limits and entitlement already used can affect the down payment. Ask for the lender’s written entitlement calculation before making an offer.'),
note('A second VA loan may be possible','It depends on remaining entitlement, qualification and a valid occupancy situation. A previous VA purchase does not automatically mean the benefit is exhausted, and it does not automatically mean the next purchase is eligible.')],['vaEligibility','vaLimits']),
page('The funding-fee table','Purchase loan percentages verified from VA for this edition.',[
table('VA purchase funding fee, unless exempt',['Down payment','First use','After first use'],[['Less than 5%','2.15%','3.30%'],['5% or more, below 10%','1.50%','1.50%'],['10% or more','1.25%','1.25%']],'The percentage applies to the base loan amount before the financed funding fee. Your lender confirms use history, down payment treatment and exemption status.'),
p('The funding fee can be paid at closing or financed into a VA purchase loan. It is different from monthly mortgage insurance. A financed fee increases principal and interest expense; an exemption can therefore affect both initial cash needs and the loan balance.'),
list('Ask the lender to verify any exemption',['VA disability compensation, including qualifying entitlement to compensation where retirement or active-duty pay is received instead.','A qualifying surviving spouse receiving Dependency and Indemnity Compensation.','Certain proposed or memorandum ratings establishing qualifying compensation eligibility before closing.','An active-duty Purple Heart recipient with the required evidence before closing.']),
note('Zero down does not mean zero closing cash','Other lender, title, prepaid tax/insurance, escrow and transaction expenses may remain. On a purchase loan, VA says only the funding fee can be financed as part of the loan in this way; use the actual Loan Estimate for the rest.')],['vaFees']),
page('How the fee changes the payment','Illustrative $400,000 purchase, 30-year fixed loan at 6.00%.',[
table('Worked scenarios, not rate quotes',['Scenario','Base loan + fee','Illustrative P&I'],[['0% down, first use, not exempt',`$400,000 + $8,600 = $408,600`,pi(408600,6)],['0% down, subsequent use, not exempt','$400,000 + $13,200 = $413,200',pi(413200,6)],['5% down, not exempt','$380,000 + $5,700 = $385,700',pi(385700,6)],['10% down, not exempt','$360,000 + $4,500 = $364,500',pi(364500,6)],['0% down, funding-fee exempt','$400,000 + $0 = $400,000',pi(400000,6)]]),
p('P&I means principal and interest only. Add buyer-based property taxes, homeowners/wind insurance, flood coverage if selected or required, and association charges. The down payments above are $0, $20,000 or $40,000; other closing costs and reserves are additional. Do not compare monthly payments without comparing the cash used to obtain them.'),
table('Rate sensitivity on a hypothetical $400,000 loan',['Illustrative fixed rate','30-year monthly P&I'],[[ '5.00%',pi(400000,5)],['6.00%',pi(400000,6)],['7.00%',pi(400000,7)]]),
note('Use a dated lender quote','These selected rates teach payment sensitivity. They are not current advertised rates, APRs, or an offer of credit. Actual pricing depends on the borrower, property, points, lock and lender.')],['vaFees']),
page('Debt ratio and residual income','VA evaluates the money remaining as well as the ratio.',[
p('Debt-to-income ratio compares qualifying monthly debt and housing obligations with qualifying gross income. A hypothetical $3,200 in total monthly obligations divided by $8,000 qualifying income is 40%. The regulation uses 41% as a guideline with additional review provisions, not an automatic universal ceiling. Lenders may apply additional requirements.'),
table('VA South region residual-income guideline',['Household size','Loan $80,000 or more'],[['1','$441 per month'],['2','$738 per month'],['3','$889 per month'],['4','$1,003 per month'],['5','$1,039 per month']],'38 CFR 36.4340(e). Florida and Alabama are in the South region. For more than five household members, the table adds $80 for each additional member up to seven. Separate amounts apply below $80,000.'),
p('Residual income is what remains after the lender’s required deductions for taxes, shelter costs, debts and other obligations. It is not simply gross income minus the mortgage. The regulation includes conditions for military adjustments and additional review. Household counting and qualifying income require the underwriter’s calculation.'),
note('Approval is not your spending target','Childcare, savings goals, travel, maintenance, support commitments and your comfort with uncertainty belong in the household budget even when a loan meets underwriting guidelines.')],['vaUnderwriting']),
page('Assemble a lender-ready file','Explain the facts once, and keep the documentation current.',[
list('Common starting documents, subject to lender requirements',['Identity, COE/service records, and applicable disability or funding-fee exemption evidence.','Recent Leave and Earnings Statements or pay statements, employment history and income documents requested by the lender.','PCS orders, expected duty location, and any income change relevant to the move.','Bank and investment statements showing funds for closing and reserves.','Information about current real estate, mortgages, leases and debts.','Explanations and supporting records for unusual deposits, income gaps, recent credit events or self-employment.']),
p('Tell the lender about expected separation, retirement, a spouse’s employment transition, a sale that must close first, or a planned assumption of the existing home loan. Stable continuing income and available funds are central to the analysis. Avoid moving funds or opening new debt without discussing the effect on the file.'),
worksheet('Your financing control sheet',['Lender / loan officer / secure upload portal:','COE / entitlement / funding-fee status confirmed:','Comfortable total payment / lender maximum:','Conditions / owner / next deadline:'])],['vaEligibility','vaUnderwriting','preapproval']),
page('Appraisal, condition and occupancy','The benefit finances an eligible home under the program’s rules.',[
p('A VA appraisal evaluates value and VA minimum property requirements; it does not replace an independent home inspection. Schedule the inspection and appropriate specialist follow-up while the contract gives you options. Discuss any required repairs, value issue, condominium project review, leasehold terms or unusual property features early.'),
p('VA purchase financing is intended for eligible occupancy, not a loan selected merely to finance an investment property. Explain your actual occupancy plans to the lender, especially with deployment, PCS timing, a spouse occupying, or a prior residence you intend to rent. Ask the lender to document the applicable rule or exception; do not assume every military absence qualifies.'),
table('If a problem appears',['Issue','Next conversation'],[['Appraisal below contract price','Review available contractual and VA/lender options with the agent and lender'],['Required repair','Who completes it, when, with what verification?'],['Project or leasehold issue','What exact document or requirement remains unresolved?'],['Occupancy timing conflict','What facts and evidence support the permitted occupancy arrangement?']]),
note('Keep the contract protections clear','Ask the agent and lender to explain the VA-specific provisions and deadlines before signing. Do not assume a generic purchase agreement covers every financing concern.')],['vaBuying','vaEligibility']),
page('Credits, concessions and cash to close','The category of a seller-paid cost matters.',[
p('VA distinguishes ordinary closing-cost credits from seller concessions. Its current guidance limits seller concessions to 4% of the home’s reasonable value, while not imposing that same cap on ordinary closing-cost credits. Examples of concessions include paying the funding fee, debt payoff, or prepaying the buyer’s hazard insurance. Have the lender classify each requested item before negotiating.'),
table('Hypothetical cash-to-close reconciliation',['Item','Example'],[['Closing costs, prepaids and escrow','$12,000'],['Eligible negotiated seller credit','-$7,000'],['Earnest money already deposited','-$2,000'],['Remaining example cash to close','$3,000']],'Assumes zero down, a separately financed funding fee, and lender approval of all credits. Any appraisal gap, down payment, repair or non-financeable item adds to the need.'),
p('The Loan Estimate and Closing Disclosure should explain the actual loan, credits, prepaids and cash to close. For most covered mortgages, you must receive the Closing Disclosure at least three business days before consummation. The lender and closing professional calculate that date and handle changes that require a new waiting period.'),
note('Protect closing funds','Verify wire instructions by calling a trusted number you already know for the closing office. A last-minute email changing banking instructions needs independent confirmation.')],['vaFees','disclosure','trid']),
page('Keep the benefit useful after closing','Your exit plan deserves attention before the next set of orders.',[
list('After closing',['Save the final Closing Disclosure, note, mortgage/deed of trust, title policy and insurance documents.','Confirm the first payment date, servicer, escrow details and any direct-pay obligations.','Apply for property-tax benefits for which you actually qualify.','Review insurance when occupancy or rental use changes.','If you sell through an assumption, obtain a release of liability and separately resolve entitlement.','If considering a refinance, compare total cost, break-even horizon and required benefit, using current lender and VA guidance.']),
table('Frequent questions',['Question','Answer'],[['Does the COE guarantee approval?','No. Borrower and property underwriting are separate.'],['Does VA set my mortgage rate?','No. The lender prices the loan; compare offers.'],['Is every veteran funding-fee exempt?','No. Verify the qualifying exemption.'],['Does an assumption automatically restore entitlement?','No. Release of liability and entitlement restoration are separate.']]),
worksheet('Your next conversation',['Remaining question / document needed:','Loan comparison date / planned purchase timing:'])],['vaFees','vaLimits','vaAssume','vaLiability'])]},
{slug:'va-loan-assumption-guide',category:'VA financing',audience:'military',shortTitle:'VA loan assumptions',title:'The rate is only the beginning.',subtitle:'A buyer and seller guide to VA assumptions, equity gaps, liability, entitlement, and closing.',answer:'A VA assumption lets an approved buyer take over an existing VA loan under its remaining terms, subject to the applicable approval process. Evaluate the equity gap, cash needs, servicer timeline, seller release of liability, and entitlement treatment before treating a low existing rate as a complete deal.',pages:[
page('Understand what continues','The existing balance and remaining term shape the opportunity.',[
p('Ask the current servicer for its assumption process, required documents and current review timeline. Do not rely on a listing’s “assumable” label as approval of the buyer or transaction. The buyer must meet the applicable credit and financial requirements, and the required transfer process must be completed.'),
table('Information to obtain first',['Loan fact','Why it matters'],[['Current principal balance and payment','Determines the debt being assumed'],['Interest rate and remaining term','Defines the remaining amortization'],['Escrow, fees and account status','Affects monthly payment and closing reconciliation'],['Servicer assumption package','Sets the submission and approval process'],['Seller liability and entitlement plan','Protects the seller’s obligations and future benefit']]),
note('Veteran status and assumption approval differ','An eligible non-veteran buyer may be able to assume a VA loan, subject to approval. Substituting entitlement requires a qualifying veteran buyer with sufficient entitlement and the required approval; it is not available merely because a buyer assumes the payments.')],['vaAssume','vaLiability']),
page('Calculate the equity gap','The purchase price can be much larger than the remaining loan.',[
table('Hypothetical assumption purchase',['Item','Amount'],[['Negotiated purchase price','$425,000'],['Existing principal to be assumed','$285,000'],['Initial price-minus-balance equity gap','$140,000'],['0.5% assumption funding fee on $285,000, if not exempt','$1,425'],['Other illustrative closing costs','$4,500'],['Example total cash before deposits/credits','$145,925']]),
p('The exact payoff/assumption balance, escrow adjustments, fee treatment, credits and closing costs must come from the servicer and settlement statement. The equity gap is not automatically financed by the assumption. If additional borrowing is proposed, confirm whether the servicer permits it, how it is secured, how it affects qualification, and what its payment and costs will be.'),
note('A low rate can require substantial liquidity','Compare the full cash commitment with a new-loan option and the reserves you need after closing. Do not empty an emergency fund simply to obtain an attractive interest rate.'),
worksheet('Your equity-gap worksheet',['Contract price minus confirmed assumption balance:','Funding fee status / other costs / credits / deposits:','Verified cash source / additional financing approval:'])],['vaFees','vaAssume']),
page('Compare the remaining payment fairly','The term and cash invested must stay visible.',[
table('Illustrative principal-and-interest comparison',['Scenario','Monthly P&I'],[['$285,000 assumed balance, 3.00%, 25 years remaining',pi(285000,3,25)],['$285,000 new loan, 6.00%, 25 years',pi(285000,6,25)],['$285,000 new loan, 6.00%, 30 years',pi(285000,6,30)]]),
p('These selected rates and terms are hypothetical, not quotes or a representation of an available assumption. They illustrate why both the rate and remaining term matter. The actual existing payment may differ because the loan’s original schedule, escrow, modifications or other terms must be reviewed.'),
p('For a real decision, compare options at the same purchase price and show the different cash requirements. Add any second-loan payment, taxes, insurance, flood coverage, association costs and reserve needs. A lower first-mortgage payment can be partly offset by expensive additional financing or a large cash investment.'),
note('Do not restart the clock on paper','An assumption normally continues the existing loan’s remaining terms. Comparing it with a new 30-year loan without identifying that difference can overstate monthly savings or obscure total interest.')],['vaAssume','vaFees']),
page('Protect the seller in two separate ways','Release of liability and entitlement are not interchangeable.',[
table('Seller protection',['Protection','What it does','What it does not establish'],[['Release of liability','Addresses the seller’s liability under the approved transfer','Does not by itself restore VA entitlement'],['Substitution/restoration of entitlement','Addresses whether the seller’s VA benefit is released or restored under applicable requirements','Does not replace a written liability release'],['Buyer payment arrangement','Describes who is expected to pay','Is not formal servicer approval or either protection above']]),
p('VA Form 26-10291 specifically addresses assumption and entitlement acknowledgment. A seller whose entitlement remains tied to the assumed loan may have less entitlement available for another purchase, and the consequences can persist beyond the closing. Discuss the next-home financing plan before accepting assumption terms.'),
list('Seller file before closing',['Written servicer approval of the assumption.','Written release-of-liability documentation applicable to the transaction.','Written entitlement substitution/restoration determination, or informed acknowledgment that entitlement remains tied up.','A lender review of the seller’s next purchase if future VA financing is part of the plan.']),
note('Do not rely on “the buyer will refinance later”','A future refinance is a possibility, not a guarantee. The buyer’s income, credit, property value and rates can change.')],['vaAssume','vaLiability','vaLimits']),
page('Build the timeline around the servicer','Use milestones and written status, not a promised universal closing time.',[
table('Assumption sequence',['Milestone','Owner / evidence'],[['Initial inquiry','Servicer confirms process, package and contacts'],['Contract','Agent/closing professional coordinates assumption terms and deadlines'],['Complete submission','Buyer supplies required credit, income, asset and transaction records'],['Review and conditions','Servicer identifies missing items and qualification conditions'],['Approval and seller protections','Written assumption, liability and entitlement decisions'],['Closing coordination','Servicer, title/closing office, insurance and parties align documents'],['Post-closing verification','Confirm account transfer, payments and retained records']]),
p('Ask when the servicer considers the package complete, how status is obtained, how long its current queue is, and what triggers additional review. Confirm rate-lock or other costs for any separate financing. Keep the seller’s loan current throughout the process and have the closing professional reconcile payments and escrow.'),
note('Use a contract that matches the uncertainty','Discuss extension rights, deposits, financing contingencies, required cooperation, and remedies with the agent and closing attorney. Do not assume the timeline of a standard new mortgage applies.')],['vaAssume','vaLiability']),
page('Questions to resolve before proceeding','Use this as a joint buyer, seller and servicer agenda.',[
table('Frequent questions',['Question','Practical answer'],[['Can the buyer simply start making payments?','That does not establish an approved assumption or seller release.'],['Is the funding fee always due?','VA lists 0.5% for assumptions; confirm any applicable exemption and treatment.'],['Does the seller keep the same entitlement available?','Not necessarily. Verify substitution/restoration in writing.'],['Can the equity gap be financed?','Only if permitted and approved; compare the added payment and terms.'],['How long does it take?','Use the actual servicer’s current process and your complete-file milestones.']]),
worksheet('Your assumption decision',['Servicer contact / package complete date:','Cash needed / verified source / reserve remaining:','Release of liability / entitlement decision:','Closing target / extension and backup plan:']),
note('A useful assumption is a complete transaction','The strongest opportunity combines acceptable cash needs, sustainable ownership costs, realistic timing, approved documents, and informed seller protection.')],['vaFees','vaAssume','vaLiability'])]}
];
