import {readFileSync} from 'node:fs';
import {p,note,list,table,worksheet,page,money,payment} from './schema.mjs';
import {directoryPages} from './base-directories.mjs';
const bah=JSON.parse(readFileSync(new URL('./bah-2026.json',import.meta.url)));
const bases=[
{slug:'nas-pensacola',name:'NAS Pensacola',mha:'FL064',zip:'32508',county:'Escambia',sources:['nas','nasOverview'],phone:'850-452-5168',office:'NAS Pensacola Housing Service Center',context:'NAS Pensacola supports aviation training and multiple tenant commands. Confirm whether your daily reporting location is on NAS Pensacola itself, Corry Station, or Saufley Field; shared administrative support does not make them the same commute.',areas:['Warrington and Navy Point','Perdido Key and southwest Pensacola','West Pensacola and Beulah'],route:'Use the actual authorized NAS gate and work building, and ask the sponsor about access for every traveler. A route to the museum or a visitor entrance may not represent your daily commute.',priority:'Training status can affect housing eligibility and the appropriate length of a housing commitment. Confirm your orders, expected course timeline and any later move before signing a long lease or buying.'},
{slug:'corry-station',name:'Corry Station',mha:'FL064',zip:'32511',county:'Escambia',sources:['nas','nasOverview'],phone:'850-452-5168',office:'NAS Pensacola Housing Service Center',context:'Corry Station is supported by the NAS Pensacola organization but is a distinct work destination. Use Corry Station in your route checks and confirm the exact command, gate and reporting instructions with your sponsor.',areas:['Myrtle Grove and Warrington','West Pensacola and Bellview','Beulah and other inland alternatives'],route:'Compare the route to Corry itself and the separate trips you expect to NAS Pensacola services. A listing described as near NAS may be convenient for a different installation than your work location.',priority:'Students and permanent-party personnel may have different unaccompanied-housing requirements. Verify your category and off-base authorization before paying an application fee or deposit.'},
{slug:'saufley-field',name:'Saufley Field',mha:'FL064',zip:'32509',county:'Escambia',sources:['nasOverview','nas'],phone:'850-452-5168',office:'NAS Pensacola Housing Service Center',context:'Saufley Field receives installation support through NAS Pensacola. Plan around your specific Saufley work location rather than using the NAS Pensacola main gate as the destination in every housing search.',areas:['Bellview and west Pensacola','Beulah and northwest Pensacola','Cantonment area alternatives'],route:'Test the route to your actual Saufley building and confirm gate access with the gaining unit. Add the separate drives required for installation services, childcare and healthcare.',priority:'Ask the gaining office which services are on Saufley and which require a trip to another installation. That answer can matter more to the weekly schedule than the straight-line distance to work.'},
{slug:'nas-whiting-field',name:'NAS Whiting Field',mha:'FL064',zip:'32570',county:'Santa Rosa',sources:['whiting','navyHousing'],phone:'850-623-9726',office:'NAS Whiting Field Housing Service Center',context:'NAS Whiting Field is in the Milton area. Confirm the training command, daily reporting point, anticipated schedule and whether later training changes the place you need to reach.',areas:['Milton and the Whiting Field area','Pace and Pea Ridge','Other Santa Rosa County alternatives'],route:'Use the assigned reporting point at Whiting Field and the expected report time. Compare the entire route from each home, including school or childcare stops, instead of treating all Milton or Pace addresses alike.',priority:'A training timeline and changing flight schedule can affect housing duration and commuting needs. Obtain the best available command information before choosing a purchase horizon or lease term.'},
{slug:'eglin-afb',name:'Eglin AFB',mha:'FL056',zip:'32542',county:'Okaloosa',sources:['eglin','eglinHousing'],phone:'850-882-4533, extension 3',office:'Eglin Military Housing Office',context:'Eglin supports the 96th Test Wing and a broad installation mission. The precise work area matters: a generic route to Eglin AFB can conceal a substantial difference between gates, work centers and associated locations.',areas:['Niceville and Valparaiso','Shalimar and Fort Walton Beach','Crestview and other north-county alternatives'],route:'Confirm the authorized gate and work center before comparing homes. Test routes at the actual shift time and include any bridge, toll or alternate-route implications relevant to the address.',priority:'The official 2026 BAH area is FL056, EGLIN AFB, FL. Use the duty ZIP and finance determination; do not substitute a home ZIP or a mislabeled rate table.'},
{slug:'hurlburt-field',name:'Hurlburt Field',mha:'FL056',zip:'32544',county:'Okaloosa',sources:['hurlburt'],phone:'850-884-7505',office:'Hurlburt Military Housing Office',context:'Hurlburt Field has its own reporting location and housing office. A home advertised for the broader Eglin area should still be evaluated against your Hurlburt gate, work schedule and household needs.',areas:['Mary Esther and Fort Walton Beach','Navarre and Holley area alternatives','Other Okaloosa and Santa Rosa County addresses'],route:'Compare the actual commute from both sides of Hurlburt at your shift time. Record recurring delays, alternate routes and the effect of a separate school or childcare trip rather than assigning a fixed commute to an entire community.',priority:'A Navarre address and a Fort Walton Beach address can involve different county services and school districts. Verify the exact parcel and assigned school through the relevant district rather than assuming the installation determines them.'},
{slug:'duke-field',name:'Duke Field',mha:'FL056',zip:'32531',county:'Okaloosa',sources:['duke','eglinHousing'],phone:'850-882-4533, extension 3',office:'Eglin Military Housing Office, with gaining-unit confirmation',context:'Duke Field is associated with the 919th Special Operations Wing. Confirm your specific unit, duty status, reporting schedule and entitlement with the gaining organization; Reserve, active-duty and other assignments can have different relocation circumstances.',areas:['Crestview area addresses','Niceville area alternatives','Other north Okaloosa County options'],route:'Route to the Duke Field work location, not Eglin’s main administrative area. Compare commute reliability and the frequency of trips to other installation services across your actual duty schedule.',priority:'Do not infer a full PCS allowance from an association with Duke Field. Orders, duty status, duration and finance guidance control the benefits available for your move.'},
{slug:'tyndall-afb',name:'Tyndall AFB',mha:'FL063',zip:'32403',county:'Bay',sources:['tyndall'],phone:'850-283-2737',office:'Tyndall Military Housing Office',context:'Tyndall AFB is in Bay County, east of Panama City. Contact the MHO as soon as the assignment is known and confirm your work location, sponsor, housing application process and after-hours arrival instructions.',areas:['Parker and Callaway','Panama City area addresses','Mexico Beach and other eastern alternatives'],route:'Test the actual route to the assigned Tyndall gate and work center. Compare eastern and western alternatives with your daily schedule and essential services; do not use a Panama City Beach route as a proxy for every Bay County address.',priority:'Tyndall housing and community choices require property-specific condition, insurance and storm planning. A newly renovated or rebuilt home still needs normal inspection, permit, insurance and title review.'},
{slug:'nsa-panama-city',name:'NSA Panama City',mha:'FL063',zip:'32407',county:'Bay',sources:['nsa','navyHousing'],phone:'850-234-4248',office:'NSA Panama City Housing Service Center',context:'NSA Panama City is a different installation from Tyndall AFB. Confirm the gaining command and use the NSA reporting location in every housing and travel plan. The Navy HSC provides local housing assistance and eligibility guidance.',areas:['Panama City Beach area addresses','Panama City and St. Andrews area alternatives','Other Bay County addresses matched to the work route'],route:'Compare the route to NSA Panama City, including any bridge crossing for the specific address. Test at the actual report time and consider seasonal travel patterns without assuming a fixed year-round commute.',priority:'Discuss accompanied versus unaccompanied housing and your assignment status with the HSC. A planned off-base purchase or lease should follow confirmation of eligibility and reporting requirements.'}
];
export const guides=bases.map(b=>{
 const area=bah.areas[b.mha],r=area.rates,common=['E-1','E-2','E-3','E-4','E-5','E-6','E-7','E-8','E-9'];
 const officers=['W-1','W-2','W-3','W-4','W-5','O-1E','O-2E','O-3E','O-1','O-2','O-3','O-4','O-5','O-6'];
 const rateRows=grades=>grades.map(g=>[g,money(r[g].withDependents),money(r[g].withoutDependents)]);
 const pi=payment(300000,6,360),other=350+275+75+50,total=pi+other;
 return {slug:`pcs-${b.slug}`,category:'Installation relocation',audience:'military',shortTitle:`${b.name} PCS`,title:`Your move to ${b.name}.`,subtitle:'A base-specific PCS field guide with official 2026 BAH, housing decisions, cash planning, arrival checklists, and an exit strategy.',answer:`Start your ${b.name} move by confirming the gaining unit, orders, sponsor and housing eligibility. Build the housing budget with the official ${area.name} BAH area (${b.mha}), then verify the actual work route, complete ownership costs and your reporting timeline.`,pages:[
 page('Your installation brief','Begin with the work location and the people responsible for your arrival.',[
 p(b.context),table('Verified starting points',['Item','Detail'],[['Installation',b.name],['County',b.county+' County, Florida'],['BAH planning ZIP / area',`${b.zip} / ${b.mha} / ${area.name}`],['Government housing contact',b.office],['Housing office phone',b.phone],['Rate edition','2026 DTMO tables, retrieved September 6, 2026']]),
 note('The first local question',b.priority),
 p('Office contacts are checked for this edition, but staffing, hours, gate access, availability and instructions can change. Use the linked official source and your sponsor before travel. This independent real estate guide does not replace orders, command instructions or government counseling.')],[...b.sources,'bah']),
 ...directoryPages(b.slug),
 page('A workable PCS calendar','This is a planning sequence, not a command deadline or guaranteed closing schedule.',[
 table('Illustrative countdown',['Timing','Focus'],[['90 or more days out','Confirm assignment, sponsor, finance/transportation counseling and household needs'],['60 days out','Compare housing paths, apply for eligible housing, arrange lodging and lender preapproval if buying'],['30 days out','Confirm shipment, inspections/contract dates, schools, insurance and document packet'],['7 days out','Reconfirm arrival instructions, lodging, cash access, travel documents and contacts'],['Arrival week','Report as directed, coordinate housing check-in and shipment delivery, document condition'],['First month','Complete finance follow-up, household setup, records and any purchase obligations']]),
 p('If orders arrive late, compress the research sequence rather than skipping critical approvals. A temporary housing plan can preserve the ability to inspect and compare properties. Do not make a nonrefundable commitment solely because a projected report date appears likely.'),
 worksheet('Your controlling dates',['Report-no-later-than date / approved leave or travel:','Shipment pickup / delivery window / lodging:','Lease or purchase deadlines / backup housing:'])],['pcs','relocation']),
 page('Choose the housing path first','Government guidance, a private lease and a purchase solve different problems.',[
 table('Three options to compare',['Option','Confirm before committing'],[['Installation / privatized housing','Eligibility, waitlist, offered unit, lease, utilities, pets and move-in timing'],['Community rental','Total move-in cash, lease terms, military termination review, condition and commute'],['Purchase','Expected ownership horizon, preapproval, closing cash, full monthly cost and exit plan']]),
 p(`Contact ${b.office} at ${b.phone} about your situation. Ask whether student, unaccompanied, accompanied or duty-status rules affect the options. Availability is not promised by this guide. Request the actual lease and have the proper office or legal assistance review questions about military termination provisions.`),
 note('Short tour, uncertain assignment or unsettled budget','Consider the cost of flexibility. Buying creates transaction costs and maintenance exposure; renting can create deposits, lease obligations and renewal uncertainty. Compare both over the length of time you reasonably expect to stay.'),
 worksheet('Your housing decision',['Likely stay / uncertainty / required flexibility:','Waitlist or rental option / purchase fallback:'])],[...b.sources,'relocation']),
 page('Compare places by your actual route','These are geographic search areas to investigate, not rankings of communities.',[
 table('Starting areas for comparison',['Area','Evidence to collect'],b.areas.map(a=>[a,'Address-specific work route, housing options, total cost, parcel flood/insurance facts and district-confirmed school assignment'])),
 p(b.route),
 list('Run a useful route test',['Use the exact gate and work building authorized for your assignment.','Check more than one weekday at the expected report and return times.','Record normal time, a delayed trip, and a practical alternate route.','Add childcare, school, second workplace and essential appointments.','Compare any tolls, fuel, parking or vehicle needs in the household budget.']),
 note('Choose using your own priorities','Evaluate property features, accessibility, budget, services and route evidence. Community-wide labels cannot establish the suitability of an individual home or school. Verify school assignment directly for the exact address.')],[...b.sources]),
 page('2026 BAH: enlisted grades',`${area.name} · ${b.mha} · monthly published rates`,[
 table('Official monthly rates',['Pay grade','With dependents','Without dependents'],rateRows(common),'Source: DTMO 2026 BAH all-locations ASCII download. E-1 through E-9 shown. Amounts are the published rate schedule, not a determination of an individual entitlement.'),
 p('BAH generally reflects the permanent duty location, pay grade and dependency status under applicable rules. The number of dependents does not create a separate rate for each child. Your finance office confirms the applicable duty ZIP, status, effective date, rate protection, dual-military circumstances and any exception.'),
 note('Your home ZIP is not a shortcut',`This guide uses ${b.zip} to identify the installation planning area. Living in a different ZIP does not by itself change the duty-location rate. Verify your orders with finance before committing to a payment.`),
 worksheet('Your finance confirmation',['Pay grade / dependency status / effective date:','Confirmed BAH / other applicable allowance:'])],['bah']),
 page('2026 BAH: officer and warrant grades',`${area.name} · ${b.mha} · monthly published rates`,[
 table('Official monthly rates',['Pay grade','With dependents','Without dependents'],rateRows(officers),'Source: DTMO 2026 tables. O-E categories require the applicable prior-enlisted/warrant service eligibility; do not select them solely because the monthly amount is higher.'),
 note('Use the official lookup for other grades','This page includes common officer and warrant grades through O-6. The original DTMO download and lookup provide the complete schedule. Finance determines eligibility, not this table.')],['bah']),
 page('Translate BAH into a housing budget','An allowance is one income input, not the same as a comfortable mortgage payment.',[
 table('Hypothetical $300,000 loan, 6.00%, 30 years',['Monthly component','Illustration'],[['Principal and interest',money(pi)],['Buyer-based property tax','$350'],['Homeowners / wind','$275'],['Flood coverage','$75'],['HOA','$50'],['Total illustrated housing payment',money(total)],['E-5 with-dependents published BAH',money(r['E-5'].withDependents)],['Housing cost minus that BAH',money(total-r['E-5'].withDependents)]]),
 p('The selected interest rate, loan, taxes, insurance and HOA are hypothetical, not local quotes or market averages. A negative final difference means the illustrated payment is below that BAH amount. Add utilities, maintenance, emergency reserves and other household costs before deciding what is comfortable. Any financed VA funding fee would also change principal.'),
 note('Price and payment are not interchangeable','Ask the lender for an actual Loan Estimate and the county/insurer for address-specific costs. A seller’s current tax bill may understate the buyer’s later bill after reassessment.')],['bah','flSOH','vaFees']),
 page('Cash for the move and for the home','Keep reimbursements, closing funds and reserves separate.',[
 table('Hypothetical cash-flow plan',['Item','Example planning amount'],[['Temporary lodging paid before reimbursement','$2,400'],['Travel, meals and fuel paid initially','$900'],['Deposits / utility setup','$650'],['Storage or delivery contingency','$600'],['Initial move cash example','$4,550'],['Separate purchase cash / repair reserve','Use lender estimate and inspection-based plan']],'Amounts are invented planning placeholders, not authorized reimbursement rates. A cost being necessary does not automatically make it reimbursable.'),
 p('DTMO increased the standard maximum TLE period to 21 days for a move to a CONUS permanent duty station, effective November 27, 2024. TLE is partial reimbursement subject to the governing rules, eligible days, documentation and finance determination; it is not a promise that every hotel expense will be paid. Ask about your itinerary and any special authorization.'),
 note('Do not spend expected reimbursement twice','Maintain enough liquidity for charges due before a voucher is paid. Keep itemized receipts and ask finance about lodging, dependents, travel-card requirements and any advance before relying on them.')],['tleDays','tle','pcs']),
 page('Household goods and travel records','A documented move is easier to reconcile and resolve.',[
 list('Before pickup',['Complete transportation counseling and confirm the shipment method, authorized limits and current procedures.','Photograph valuable items, record serial numbers, and retain important records outside the shipment.','Keep medications, essential equipment, identity documents, orders, closing records and a travel kit with you.','Confirm pickup access, parking, inventory procedures, storage needs and delivery contact details.','Ask the transportation office how to report missed dates, loss, damage or other service issues under current rules.']),
 p('At pickup and delivery, review inventories and note exceptions promptly. Save the documents and photographs in an organized file. If an item is missing or damaged, use the current official loss/damage notification and claim process; its deadlines may differ, so do not wait for a future article or assume an old deadline still applies.'),
 worksheet('Shipment and travel file',['Transportation office / shipment reference:','Carrier / pickup / required delivery / actual delivery:','Inventory exceptions / notification deadline / claim status:'])],['pcs']),
 page('Schools, healthcare and household continuity','Verify enrollment and services directly before choosing an address.',[
 p(`For ${b.name}, begin with the installation relocation office and school liaison, then the district serving the exact property. ${b.county} County is the installation county; a home across a county boundary may be served by a different district. A real estate portal’s school label does not establish current assignment, transportation, capacity or program eligibility.`),
 list('Transfer checklist',['Ask the school district about enrollment records, address verification, placement, transportation and registration timing.','Coordinate individual learning-support records and required meetings through the school professionals.','Use the appropriate military healthcare channels to plan enrollment, referrals, prescriptions and continuity of care.','If applicable, coordinate EFMP and accessibility needs through the authorized offices before finalizing housing.','Ask about childcare availability and enrollment; do not assume a place is reserved because a center exists.','Plan spouse employment, vehicle/identity records, pets, utilities and emergency contacts.']),
 note('Keep sensitive records in the right channel','Send medical, education, identity and financial records through the responsible organization’s secure process. Your housing search does not require posting those records in a shared listing conversation.'),
 worksheet('Household continuity plan',['School liaison / district confirmation / childcare status:','Healthcare transfer / appointment / records owner:'])],['relocation']),
 page('Coastal condition and storm planning','Price the property’s exposure before you sign.',[
 p('Obtain property-specific homeowners/wind and flood quotes during the contract review period. Ask about roof condition, inspection requirements, exclusions, replacement-cost assumptions, deductibles and binding timing. Standard homeowners coverage generally excludes flood. A lender’s flood requirement and your own risk decision are separate questions.'),
 table('Illustrative storm reserve',['Example','Cash implication'],[['Dwelling coverage $400,000 with 2% deductible','$8,000 deductible exposure'],['Same coverage with 5% deductible','$20,000 deductible exposure'],['Difference to plan for','$12,000']],'Read the actual policy for triggers and calculation basis. These examples are not a quote or recommendation of a deductible.'),
 list('Arrival preparation',['Locate official county and installation emergency information.','Review evacuation and shelter options for your household, pets and accessibility needs.','Identify supplies, documents, transportation and an out-of-area contact.','Photograph the home’s move-in condition and retain policy details offline.']),
 note('Choose based on the parcel','Flood zone, drainage, elevation, building condition and coverage can vary within a community. Obtain the applicable records and professional review for the exact property.')],['insurance','hurricane','flood']),
 page('Arrival and the next PCS','Close the move and retain a practical exit option.',[
 table('First-week priorities',['Action','Confirmation'],[['Report and in-process','Gaining unit instructions completed'],['Housing check-in','Lease/deed, condition record, keys and utilities'],['Shipment delivery','Inventory and exceptions documented'],['Finance follow-up','Voucher, receipts, allowance changes and questions'],['Household services','School, childcare, healthcare and emergency plan'],['Homeownership tasks','First mortgage payment, insurance and tax-exemption calendar']]),
 p('Before buying, compare what selling or renting the property could require if the next assignment arrives early. Use conservative resale, vacancy, management, repairs and carrying-cost assumptions. Confirm any association, lease, lending or insurance restrictions on rental use. If considering a VA assumption as a seller, separately address liability release and entitlement.'),
 worksheet('Your first-month review',['Unpaid or unresolved move expense / owner / deadline:','Home documents / insurance / first payment confirmed:','Exit strategy / reserve target / review date:']),
 note('Bring the remaining questions to your team','Gregg coordinates the property search and transaction. Your command, housing office, transportation office, finance office, lender and other professionals confirm decisions within their roles.')],['pcs','vaAssume','flSOH'])]};
});
