import {p,note,list,table,worksheet,page,money} from './schema.mjs';
export const guides=[
{slug:'seller-transaction-roadmap',category:'Selling',audience:'civilian',shortTitle:'The seller transaction',title:'Your sale, step by step.',subtitle:'A clear transaction plan from preparation and pricing to closing, proceeds, and possession.',answer:'A successful sale coordinates pricing, property preparation, disclosure, buyer qualification, contract deadlines, and closing logistics. Your strongest offer is the combination of net proceeds, terms, evidence, and the likelihood of closing.',pages:[
page('Begin with the outcome','Set the destination before choosing a list price.',[
p('Write down your move date, whether you need sale proceeds for another purchase, and your flexibility. Coordinate replacement housing and a backup plan before choosing the launch date.'),
table('The seller sequence',['Phase','Decision or deliverable'],[['Prepare','Representation agreement, objectives, disclosures, property and ownership documents'],['Price','Comparable sales, current competition, condition adjustments, initial net sheet'],['Launch','Repairs/staging choices, accurate photography, listing details, showing plan'],['Negotiate','Compare price, credits, contingencies, deposit, financing, and dates'],['Under contract','Meet disclosure/access obligations; manage inspection, appraisal, title and association work'],['Close','Confirm payoff, final figures, signing, funds, and possession'],['After the sale','Retain records and complete tax, insurance, utility, and address follow-up']]),
note('Define success in dollars and dates','A higher price can be offset by larger credits, repairs, uncertain financing, or a timing mismatch. Compare the entire agreement with your objective.'),
worksheet('Your sale brief',['Closing / possession / replacement housing plan:','Mortgage payoff / desired proceeds:'])
]),
page('Prepare the property and the file','Make informed preparation choices and disclose accurately.',[
list('Collect before launch',['Mortgage and lien information, ownership/trust/entity documents if applicable, and any power-of-attorney needs.','Survey, prior title policy, permits, warranties, repair records, and insurance-claim information you have.','Association contact, current dues, special assessments, rental/occupancy restrictions, and transfer requirements.','Existing leases, tenant notices, service contracts, solar/equipment agreements, and items excluded from the sale.','Property disclosures required for this transaction, completed honestly with professional guidance.']),
p('Ask which work is necessary for safety, insurance, financing, marketability, or presentation. A cosmetic improvement and a condition that prevents insurance coverage deserve different priority. Obtain written estimates for significant work, document completion, and avoid guaranteeing a return for every dollar spent.'),
table('Preparation decision',['Question','Useful evidence'],[['Repair or disclose and price accordingly?','Inspection or specialist opinion, written estimate, contract implications'],['Improve presentation?','Condition of competing homes and likely buyer use'],['Pre-list inspection?','Time to address findings and disclosure implications'],['Tenant-occupied?','Lease terms, notice requirements, access and possession plan']]),
note('State-specific obligations','Florida and Alabama have different legal rules and transaction customs. Your agent and closing attorney should identify the applicable disclosures and duties; a generic form is not a substitute for that review.')
]),
page('Price and launch with evidence','A useful pricing conversation separates sales evidence from seller goals.',[
p('Review recent comparable closed sales, pending activity where available, current competing listings, and differences in condition, size, location, waterfront exposure, and ownership costs. A neighbor’s asking price is evidence of competition, not proof that a buyer paid that amount. An automated estimate is one input and cannot inspect your property.'),
list('Before the listing goes live',['Approve the factual description, room counts, measurements or their source, included items, and association information.','Confirm professional photography accurately represents the property and that any virtual staging is identified.','Agree on showing instructions, notice, pet arrangements, valuables, access security, and feedback cadence.','Set the initial pricing rationale and a review date based on the actual response.','Confirm how your agent will report inquiries, showings, offers, and changes in comparable competition.']),
note('Agree on what will change the plan','A pricing review should consider qualified buyer response and current competing options. It should not follow an automatic percentage reduction every few days.'),
worksheet('Launch control sheet',['List price / supporting comparable evidence:','Preparation complete / photographer / launch date:','Showing rules / feedback method:','Review date / evidence that would trigger a change:'])
]),
page('Compare offers as complete packages','Evaluate the buyer’s obligations and your remaining exposure.',[
table('Offer comparison',['Term','What to establish'],[['Price and credits','Expected proceeds after concessions, negotiated compensation, repairs, and other costs'],['Financing evidence','Preapproval depth, loan type, down payment, proof of funds, and property eligibility'],['Deposit','Amount, due date, holder, and circumstances governing return or retention'],['Contingencies','Inspection, financing, appraisal, existing-home sale, association approval, and other rights'],['Closing and possession','Whether the dates match your move and replacement-home needs'],['Included items / repairs','Exactly what is being conveyed or completed'],['Assumption, if proposed','Servicer process, buyer cash gap, liability release, and VA entitlement implications']]),
p('Preapproval is useful but conditional. Ask about the review supporting the letter and whether the lender can work with the proposed property and schedule. If an offer relies on an assumption or a buyer’s home sale, identify the additional decision-makers and dependencies before accepting.'),
note('Written changes only','Have every negotiated change documented in the signed contract or amendment. Verbal assurances about repairs, timing, possession, or credits can create avoidable disputes.')
],['preapproval','vaAssume']),
page('Manage the contract period','Keep the property ready, the records available, and the calendar current.',[
list('Your responsibilities after acceptance',['Confirm the fully executed contract and every deadline with your agent.','Provide agreed disclosures, association documents, access, and other required information on time.','Keep utilities available for inspections, appraisal, and the final walkthrough as required.','Respond to inspection negotiations through the agreed process; obtain written repair scope and receipts.','Help the closing professional resolve liens, ownership, survey, estate, trust, or title exceptions.','Confirm any association transfer, estoppel, approval, or assessment work is underway.','Continue maintaining and insuring the property through the agreed transfer of risk and possession.']),
p('An inspection request, appraisal issue, or financing condition does not automatically end the transaction. The contract determines rights and notice deadlines. Ask what decision must be made now, what evidence is needed, and what happens if the parties do not agree.'),
worksheet('Track open matters',['Inspection decision / repair obligations:','Appraisal or finance issue / responsible person:','Title / association documents still needed:','Amendments changing closing or possession:'])
],['documents','condoFAQ']),
page('Closing day and the handoff','Know the difference between signing, disbursement, and possession.',[
p('Obtain the final seller settlement statement and review the price, mortgage payoff, liens, negotiated charges, credits, taxes, assessments, and expected proceeds. A loan balance shown online may differ from a formal payoff because of daily interest and fees. The closing professional should obtain the applicable payoff.'),
list('The final checklist',['Confirm your identification, signing appointment, approved remote-signing method, and any required witnesses or notarization.','Verify where proceeds will be sent using the closing professional’s trusted contact process.','Complete agreed repairs and retain supporting invoices or permits.','Remove belongings and provide keys, remotes, codes, and included items according to the contract.','Confirm funding and possession before cancelling coverage or handing over access.','Plan utility termination and forwarding without interrupting a required walkthrough.']),
note('A post-closing stay needs its own plan','If you remain after closing, document dates, payment, deposit, insurance, utilities, liability, and enforcement with professional guidance. Do not rely on an informal understanding.'),
p('Retain your closing statement, purchase/improvement records, payoff confirmations, and other relevant documents for your tax adviser. Discuss gain, exclusions, reporting, and out-of-state or other special circumstances with that adviser rather than assuming every sale is tax-free.')
],['documents']),
page('Your seller deadline and proceeds sheet','Use exact dates and written estimates from the people handling the transaction.',[
worksheet('Transaction control',['Listing agreement / disclosures complete:','Launch / feedback review:','Contract effective date / deposit due:','Inspection decision / repair completion:','Title / association / appraisal milestones:','Formal payoff valid through / final proceeds estimate:','Signing / funding / possession / move-out:','Replacement housing contingency / backup plan:']),
note('Keep a current net sheet','Update the proceeds estimate whenever price, credits, repair obligations, assessments, payoff timing, or negotiated costs change. The initial estimate is a planning document; the final settlement statement controls actual disbursement.')
])]},
{slug:'seller-net-proceeds',category:'Selling',audience:'civilian',shortTitle:'Seller proceeds',title:'What will you keep?',subtitle:'A seller’s net-proceeds workbook for comparing offers and planning the next move.',answer:'Net proceeds equal your sale price less payoff amounts, transaction costs, credits, and other seller obligations. Compare offers using consistent assumptions and update the worksheet when terms or timing change.',pages:[
page('Start with the right equation','Sale price and money available for your next purchase are different numbers.',[
note('Net-proceeds equation','Sale price − mortgage/liens − negotiated sale costs − buyer credits − repairs/other obligations ± prorations = estimated proceeds.'),
table('Build the inputs',['Input','Where it should come from'],[['Price','The offer or a clearly labeled pricing scenario'],['Mortgage payoff','Formal payoff estimate, including through-date and daily interest'],['Compensation','Your signed agreements and the negotiated transaction'],['Title / closing / legal','An itemized quote from the closing professional'],['Taxes / HOA / assessments','Current records and contract allocation'],['Buyer credits / repairs','The signed contract and amendments'],['Other liens or obligations','Title review, recorded liens, equipment or solar agreements']]),
p('Real estate compensation is negotiable. There is no universal commission rate in this worksheet. Enter what your agreements actually require, including any separately negotiated buyer-side compensation, without counting the same amount twice.'),
p('Keep moving, temporary housing, purchase closing costs, and post-sale taxes in a separate household cash plan. They can reduce the money available for your next move even when they do not appear as deductions on this sale’s settlement statement.')
]),
page('A worked proceeds example','Every amount on this page is a hypothetical teaching input.',[
table('Illustrative sale',['Line','Amount'],[['Sale price','$450,000'],['Mortgage payoff','− $285,000'],['Negotiated brokerage compensation, example only','− $18,000'],['Title / closing / legal estimate','− $3,200'],['Buyer credit','− $6,000'],['Prorations and other seller charges','− $2,400'],['Agreed repairs paid from proceeds','− $1,500'],['Estimated seller proceeds','$133,900']]),
p('The example subtracts $316,100 of total obligations from $450,000. It is not a quote for Pensacola closing costs or compensation. A different payoff date, title issue, credit, or assessment changes the result. Get a written estimate for the actual property.'),
table('How one change affects this example',['Change, with all else held equal','Revised proceeds'],[['Price rises by $5,000 and costs stay fixed','$138,900'],['Buyer credit rises by $4,000','$129,900'],['Additional lien payoff of $10,000','$123,900']]),
note('Check percentage-based costs','If a negotiated charge is a percentage of price, a price change also changes that charge. The simple sensitivity examples hold costs fixed only to isolate the effect.')
]),
page('Compare two offers','Evaluate the cash result and the conditions that support it.',[
table('Hypothetical comparison',['Term','Offer A','Offer B'],[['Price','$450,000','$445,000'],['Buyer credit','$10,000','$2,000'],['All other seller obligations, assumed equal','$310,100','$310,100'],['Estimated proceeds','$129,900','$132,900'],['Closing / conditions','Review the actual offer','Review the actual offer']]),
p('In this example, Offer B produces $3,000 more estimated proceeds despite its lower price. It is not automatically the better choice: financing, inspection rights, an appraisal gap, a home-sale contingency, closing timing, and possession can affect the decision.'),
list('Before choosing',['Recalculate with the costs that actually change between offers.','Read the buyer’s financing evidence and proof of cash for any gap.','Identify conditions that could reopen negotiations or prevent closing.','Confirm whether the dates avoid expensive temporary housing or a missed purchase deadline.','Ask for a net sheet that identifies estimates and unresolved charges.'])
],['preapproval']),
page('Your proceeds workbook','Bring this to the offer review and update it before closing.',[
worksheet('Sale calculation',['Proposed sale price:','Mortgage payoff / payoff through-date:','Additional liens or equipment obligations:','Negotiated compensation under all applicable agreements:','Title / closing / legal / recording:','Buyer credits / repairs / assessments:','Tax and association prorations, plus or minus:','Estimated net proceeds:']),
note('Next-move cash','Subtract planned moving costs, temporary housing, reserves, and next-purchase cash needs in a separate budget. Ask your tax adviser whether any tax reserve belongs there.')
]),
page('Questions for the closing professional','Resolve uncertainty while there is time to act.',[
list('Ask for a property-specific answer',['Is the payoff current through the expected funding date, and what is the daily interest afterward?','Does title show any additional lien, ownership, estate, trust, or signing issue?','Which tax and association amounts are prorated, and who pays special assessments under the contract?','Are any funds held back for repairs, occupancy, or another condition?','Which expenses have already been paid outside closing?','How and when will proceeds be disbursed after all conditions are satisfied?','What identity and signing documents are required?','How do we verify payment instructions through a trusted channel?']),
p('Save the final settlement statement and supporting records. Ask your agent for a closing handoff checklist covering possession, keys, utilities, insurance, warranties, and the next transaction. A clean handoff protects the result you worked to achieve.'),
worksheet('Final confirmation',['Final estimated proceeds / date prepared:','Remaining unknown charge / owner / due date:','Verified disbursement instructions confirmed with:'])
],['documents'])]}
];
