// Sources were opened or located in the September 6, 2026 research session.
// Page-level references identify the authorities supporting each section.
import {directorySources} from './base-directories.mjs';
import {journeySources} from './journey-sources.mjs';
export const sources = {
 ...journeySources,
 ...directorySources,
 nasOverview:{name:'U.S. Navy: NAS Pensacola, Corry and Saufley support',url:'https://cnrse.cnic.navy.mil/Installations/NAS-Pensacola/About/',reviewed:'2026-09-06'},
 tleDays:{name:'DTMO: CONUS Temporary Lodging Expense, 21 days',url:'https://www.travel.dod.mil/About/News/Article/Article/3981433/dod-authorizes-additional-7-days-to-conus-temporary-lodging-expense/',reviewed:'2026-09-06'},
 vaUnderwriting:{name:'38 CFR 36.4340: VA underwriting and residual income',url:'https://www.ecfr.gov/current/title-38/chapter-I/part-36/subpart-B/section-36.4340',reviewed:'2026-09-06'},
 hurricane:{name:'Florida CFO: Hurricane deductibles',url:'https://www.myfloridacfo.com/division/consumers/consumerprotections/floridashurricanedeductible',reviewed:'2026-09-06'},
 insurance:{name:'Florida OIR: Homeowners insurance',url:'https://floir.gov/property-casualty/homeowners-insurance',reviewed:'2026-09-06'},
 flood:{name:'NFIP: Buying flood insurance and waiting periods',url:'https://www.floodsmart.gov/get-insured/buy-a-policy',reviewed:'2026-09-06'},
 lease:{name:'Santa Rosa Island Authority: Leasing documents and forms',url:'https://www.sria-fla.com/administration/page/administration-leasing-documents-forms',reviewed:'2026-09-06'},
 sria:{name:'Santa Rosa Island Authority: Administration',url:'https://www.sria-fla.com/administration',reviewed:'2026-09-06'},
 navyHousing:{name:'U.S. Navy: Housing Service Center contacts',url:'https://ffr.cnic.navy.mil/Navy-Housing/Contact-Navy-Housing/',reviewed:'2026-09-06'},
 nas:{name:'U.S. Navy: NAS Pensacola housing',url:'https://ffr.cnic.navy.mil/Navy-Housing/Housing-By-Region/Southeast/NAS-Pensacola/',reviewed:'2026-09-06'},
 whiting:{name:'U.S. Navy: NAS Whiting Field contacts',url:'https://cnrse.cnic.navy.mil/Installations/NAS-Whiting-Field/Contact-Us/',reviewed:'2026-09-06'},
 nsa:{name:'U.S. Navy: NSA Panama City housing',url:'https://ffr.cnic.navy.mil/Navy-Housing/Housing-By-Region/Southeast/NSA-Panama-City/',reviewed:'2026-09-06'},
 eglin:{name:'Military OneSource: Eglin AFB installation overview',url:'https://installations.militaryonesource.mil/in-depth-overview/eglin-afb',reviewed:'2026-09-06'},
 eglinHousing:{name:'U.S. Air Force: Eglin housing',url:'https://www.housing.af.mil/Home-depricated/Units/Eglin/',reviewed:'2026-09-06'},
 hurlburt:{name:'U.S. Air Force: Hurlburt Field housing',url:'https://www.housing.af.mil/Home/Installations/Hurlburt-Field/',reviewed:'2026-09-06'},
 duke:{name:'Air Force Reserve Command: 919th Special Operations Wing',url:'https://www.afrc.af.mil/Units/919sow/',reviewed:'2026-09-06'},
 tyndall:{name:'U.S. Air Force: Tyndall AFB housing',url:'https://www.housing.af.mil/Home/Installations/Tyndall-AFB/',reviewed:'2026-09-06'},
 preapproval:{name:'CFPB: Get a preapproval letter',url:'https://www.consumerfinance.gov/owning-a-home/explore/get-a-preapproval-letter/',reviewed:'2026-09-06'},
 documents:{name:'CFPB: Documents before closing',url:'https://www.consumerfinance.gov/ask-cfpb/what-documents-should-i-receive-before-closing-on-a-mortgage-loan-en-181/',reviewed:'2026-09-06'},
 disclosure:{name:'CFPB: What is a Closing Disclosure?',url:'https://www.consumerfinance.gov/ask-cfpb/what-is-a-closing-disclosure-en-1983/',reviewed:'2026-09-06'},
 trid:{name:'CFPB: TILA-RESPA disclosure FAQs',url:'https://www.consumerfinance.gov/compliance/compliance-resources/mortgage-resources/tila-respa-integrated-disclosures/tila-respa-integrated-disclosure-faqs/',reviewed:'2026-09-06'},
 cd:{name:'CFPB: Closing Disclosure explainer',url:'https://www.consumerfinance.gov/owning-a-home/closing-disclosure/',reviewed:'2026-09-06'},
 vaFees:{name:'VA: Funding fee and closing costs',url:'https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/',reviewed:'2026-09-06'},
 vaLimits:{name:'VA: Entitlement and loan limits',url:'https://www.va.gov/housing-assistance/home-loans/loan-limits/',reviewed:'2026-09-06'},
 vaEligibility:{name:'VA: Home loan eligibility',url:'https://www.va.gov/housing-assistance/home-loans/eligibility/',reviewed:'2026-09-06'},
 vaBuying:{name:'VA: Buying with a VA-backed loan',url:'https://www.va.gov/housing-assistance/home-loans/home-buying-process/',reviewed:'2026-09-06'},
 vaAssume:{name:'VA: Assumption entitlement acknowledgment, Form 26-10291',url:'https://www.vba.va.gov/pubs/forms/VBA-26-10291-ARE.pdf',reviewed:'2026-09-06'},
 vaLiability:{name:'VA: Rights of VA loan borrowers, Form 26-8978',url:'https://www.vba.va.gov/pubs/forms/26-8978.pdf',reviewed:'2026-09-06'},
 bah:{name:'DTMO: Official BAH rates and downloads',url:'https://www.travel.dod.mil/Allowances/Basic-Allowance-for-Housing/BAH-Rate-Lookup/',reviewed:'2026-09-06'},
 pcs:{name:'Military OneSource: PCS and moving FAQs',url:'https://www.militaryonesource.mil/moving-pcs/plan-to-move/military-pcs-moving-faqs/',reviewed:'2026-09-06'},
 relocation:{name:'Military OneSource: Relocation Assistance Program',url:'https://www.militaryonesource.mil/benefits/relocation-assistance-program/',reviewed:'2026-09-06'},
 tle:{name:'Military OneSource: Temporary Lodging Expense',url:'https://www.militaryonesource.mil/benefits/temporary-lodging-expense/',reviewed:'2026-09-06'},
 flTax:{name:'Florida DOR: Property tax forms and publications',url:'https://floridarevenue.com/property/Pages/Forms.aspx',reviewed:'2026-09-06'},
 flSOH:{name:'Florida DOR: Save Our Homes and portability',url:'https://floridarevenue.com/property/Documents/pt112.pdf',reviewed:'2026-09-06'},
 alTax:{name:'Baldwin County: Assessment exemptions',url:'https://baldwincountyal.gov/government/revenue-commission/divisions/assessments/exemptions',reviewed:'2026-09-06'},
 alCalc:{name:'Baldwin County: Property tax calculator',url:'https://services.baldwincountyal.gov/PropertyTaxCalculator',reviewed:'2026-09-06'},
 condo:{name:'Florida DBPR: Condominium inspection and reserve requirements',url:'https://condos.myfloridalicense.com/inspections/',reviewed:'2026-09-06'},
 condoFAQ:{name:'Florida DBPR: Condominium FAQs',url:'https://condos.myfloridalicense.com/faqs/',reviewed:'2026-09-06'}
};
