import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
import {withReceiptConversions} from './inquiry-browser-lib.mjs';
const source=readFileSync('public/assets/costin-conversions.js','utf8');
const receipt={success:true,accepted:true,duplicate:false,receiptId:'f265e4d2-7c80-4f64-a7db-160ca199a013',captureStatus:'crm_accepted'};
function browser({storage=new Map(),blocked=false,gpc=false}={}){const events=[],analytics=[],meta=[];const env={window:{gtag:(...x)=>analytics.push(x),costinMeta:{track:x=>meta.push(x)}},navigator:{globalPrivacyControl:gpc},location:{hostname:'greggcostin.com'},CustomEvent:class {constructor(type,o){this.type=type;this.detail=o.detail;}},document:{dispatchEvent:e=>events.push(e)},localStorage:{getItem:k=>{if(blocked)throw Error('blocked');return storage.get(k)},setItem:(k,v)=>storage.set(k,v)}};vm.runInNewContext(source,env);return {...env,events,analytics,meta,api:env.window.costinConversions};}
test('only successful durable receipt statuses are accepted',()=>{const b=browser();for(const data of [{success:true},{...receipt,accepted:false},{...receipt,receiptId:'missing'},{...receipt,captureStatus:'pending'},{...receipt,duplicate:undefined}])assert.equal(b.api.accept(true,data,'inquiry-form'),false);assert.equal(b.api.accept(false,receipt,'inquiry-form'),false);assert.equal(b.analytics.length,0);assert.equal(b.api.accept(true,receipt,'inquiry-form'),true);assert.equal(b.analytics.length,1);assert.equal(b.api.isVerifiedEvent(b.events[0]),true);assert.equal(b.api.isVerifiedEvent({detail:{receipt_verified:true}}),false);});
test('duplicate receipts succeed in UI and never create a second conversion, including reload',()=>{const storage=new Map(),a=browser({storage});a.api.accept(true,receipt,'inquiry-form');a.api.accept(true,receipt,'inquiry-form');const b=browser({storage});b.api.accept(true,receipt,'inquiry-form');b.api.accept(true,{...receipt,duplicate:true,receiptId:'ba06519a-d2e0-4c6c-bdd0-273a757b7b45'},'inquiry-form');assert.equal(a.analytics.length,1);assert.equal(b.analytics.length,0);});
test('fallback, privacy and blocked storage retain their separate meanings',()=>{const b=browser({blocked:true});b.api.accept(true,{...receipt,captureStatus:'email_fallback',email:'private@example.invalid'},'untrusted-form-name');b.api.accept(true,receipt,'inquiry-form');assert.equal(b.analytics.length,1);assert.equal(b.analytics[0][2].capture_status,'email_fallback');assert.equal(b.analytics[0][2].form_id,'website-form');assert.equal(JSON.stringify(b.analytics).includes('private@'),false);assert.equal(JSON.stringify(b.analytics).includes(receipt.receiptId),false);const p=browser({gpc:true});assert.equal(p.api.accept(true,receipt,'inquiry-form'),true);assert.equal(p.analytics.length+p.meta.length,0);});
test('both legacy static handler variants become idempotent receipt gates',()=>{for(const condition of ['res.ok&&res.j.success','res.ok&&res.j.success===true']){const h=`<head></head><script>if(${condition}){document.dispatchEvent(new CustomEvent('costin:lead-success',{detail:{form_id:form.id}}));if(window.gtag)gtag('event','inquiry_submit',{event_category:'conversion'});}</script>`;const actual=withReceiptConversions(h);assert.match(actual,/costinConversions\?\.accept/);assert.doesNotMatch(actual,/new CustomEvent|inquiry_submit/);assert.equal(withReceiptConversions(actual),actual);}});
