// The 19 community guide links with one-line blurbs and their base group. Plain ESM data:
// imported by src/App.jsx (NeighborhoodsPage, base pages) AND scripts/postbuild-spa-routes.mjs,
// so the crawler-visible /communities shell lists exactly what React renders (audit idx-04).
// Add a community here when scripts/page-factory.mjs creates its public/communities/<slug>.html.
export const COMMUNITY_GROUPS = ["NAS Pensacola, Corry Station & Saufley Field","NAS Whiting Field","Eglin AFB, Hurlburt Field & Duke Field"];
export const COMMUNITY_LINKS = [
  { label: "Gulf Breeze", href: "/communities/gulf-breeze", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "Compare Gulf Breeze proper and the wider peninsula. Check bridge traffic, flood exposure and the assigned schools for each address." },
  { label: "Navarre", href: "/communities/navarre", base: "Eglin AFB, Hurlburt Field & Duke Field", blurb: "Explore mainland and beach properties in Santa Rosa County. Compare US 98 access, insurance and the route to your reporting gate." },
  { label: "Pace", href: "/communities/pace", base: "NAS Whiting Field", blurb: "Compare established subdivisions and new construction west of Milton, including lot size, association costs and the drive to Whiting Field." },
  { label: "Milton", href: "/communities/milton", base: "NAS Whiting Field", blurb: "Explore homes around the Santa Rosa County seat and routes to Whiting Field. Verify the property location and assigned school boundaries." },
  { label: "Cantonment", href: "/communities/cantonment", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "North Escambia County options include larger lots and subdivisions. Compare the exact address, utilities and route to your duty station." },
  { label: "Beulah", href: "/communities/beulah", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "Explore northwest Escambia County near the Navy Federal campus. Compare newer construction, association fees and access to west Pensacola bases." },
  { label: "Perdido Key", href: "/communities/perdido-key", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "Barrier-island homes and condos require a close look at flood coverage, association finances, use restrictions and the route to NAS Pensacola." },
  { label: "East Pensacola Heights", href: "/communities/east-pensacola-heights", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "Compare established homes near Bayou Texar and downtown Pensacola. Review property condition, elevation and your daily destinations." },
  { label: "East Hill", href: "/communities/east-hill", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "Explore historic homes and newer infill near central Pensacola. Compare renovation records, parking and the route to your reporting gate." },
  { label: "Cordova Park", href: "/communities/cordova-park", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "Established central Pensacola housing near shopping and the airport. Check the address-specific school assignment and home condition." },
  { label: "Ferry Pass", href: "/communities/ferry-pass", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "Explore north Pensacola homes with access to the university and Interstate 10. Compare property age, insurance and your full daily drive." },
  { label: "Bellview/Myrtle Grove", href: "/communities/bellview-myrtle-grove", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "Compare west Pensacola properties and routes to Corry Station and NAS Pensacola. Roof age, condition and insurance can change the monthly cost." },
  { label: "Navy Point/Warrington", href: "/communities/navy-point-warrington", base: "NAS Pensacola, Corry Station & Saufley Field", blurb: "Explore established neighborhoods near NAS Pensacola and Bayou Grande. Review elevation, flood insurance and the actual gate route." },
  { label: "Niceville/Valparaiso/Bluewater Bay", href: "/communities/niceville", base: "Eglin AFB, Hurlburt Field & Duke Field", blurb: "Compare three distinct areas east of Eglin. Review the gate route, property costs and verified school assignment for each home." },
  { label: "Fort Walton Beach", href: "/communities/fort-walton-beach", base: "Eglin AFB, Hurlburt Field & Duke Field", blurb: "Explore housing between the Eglin and Hurlburt areas. Compare year-round travel, property condition and total ownership costs." },
  { label: "Mary Esther", href: "/communities/mary-esther", base: "Eglin AFB, Hurlburt Field & Duke Field", blurb: "Compare properties around Hurlburt Field and Santa Rosa Sound. Check gate access, US 98 traffic and address-specific insurance quotes." },
  { label: "Shalimar", href: "/communities/shalimar", base: "Eglin AFB, Hurlburt Field & Duke Field", blurb: "Explore housing around the bayous south of Eglin. Compare the gate route, flood exposure and the documents for waterfront properties." },
  { label: "Destin", href: "/communities/destin", base: "Eglin AFB, Hurlburt Field & Duke Field", blurb: "Compare coastal homes and condos with the year-round drive to Eglin or Hurlburt. Review association costs, insurance and permitted property uses." },
  { label: "Crestview", href: "/communities/crestview", base: "Eglin AFB, Hurlburt Field & Duke Field", blurb: "Explore north Okaloosa County homes and new construction. Compare Highway 85 travel to Duke Field or Eglin with the full monthly housing cost." },
];
