// Generated by scripts/build-identity-record.mjs. Edit content/entity/entity.json and evidence.json.
export const IDENTITY = {
  "ids": {
    "person": "https://greggcostin.com/#gregg",
    "team": "https://greggcostin.com/#team",
    "brokerage": "https://greggcostin.com/#brokerage",
    "portrait": "https://pensacolamilitaryhousing.com/#portrait",
    "logo": "https://pensacolamilitaryhousing.com/#logo"
  },
  "name": "Gregg Costin",
  "suffix": "MRP, ABR, SRS, RENE, FMS",
  "jobTitle": "Realtor",
  "shortBio": "Realtor with Levin Rinke Realty, licensed in Florida and Alabama; retired USAF Combat Systems Officer; serves Pensacola, the Florida Panhandle and Alabama's Gulf Shores and Orange Beach.",
  "military": {
    "branch": "USAF",
    "rank": "Captain",
    "role": "E-3 AWACS Combat Systems Officer",
    "personalPcsMoves": 11,
    "careerLength": "two decades",
    "priorEnlisted": true
  },
  "positioning": "Pensacola's #1 military relocation REALTOR®",
  "credentials": [
    {
      "name": "Florida Real Estate Sales Associate License",
      "category": "license",
      "by": {
        "@type": "GovernmentOrganization",
        "name": "Florida Department of Business and Professional Regulation",
        "url": "https://www.myfloridalicense.com/"
      },
      "identifier": "SL3630964",
      "url": "https://www.myfloridalicense.com/portalsearches/VerifyLicensee/LicenseDetail?ID=AC5740A2FFB1E506A82D86E377ACE3EB"
    },
    {
      "name": "Alabama Real Estate Salesperson License",
      "category": "license",
      "by": {
        "@type": "GovernmentOrganization",
        "name": "Alabama Real Estate Commission",
        "url": "https://arec.alabama.gov/"
      },
      "identifier": "000171694-0",
      "url": "https://arec.alabama.gov/apps/LicenseSearch/Home/Details/163221"
    },
    {
      "name": "Military Relocation Professional (MRP)",
      "category": "certification",
      "by": {
        "@type": "Organization",
        "name": "National Association of Realtors"
      }
    },
    {
      "name": "Accredited Buyer's Representative (ABR)",
      "category": "certification",
      "by": {
        "@type": "Organization",
        "name": "National Association of Realtors"
      }
    },
    {
      "name": "Seller Representative Specialist (SRS)",
      "category": "certification",
      "by": {
        "@type": "Organization",
        "name": "National Association of Realtors"
      }
    },
    {
      "name": "Real Estate Negotiation Expert (RENE)",
      "category": "certification",
      "by": {
        "@type": "Organization",
        "name": "National Association of Realtors"
      }
    },
    {
      "name": "Florida Military Specialist (FMS)",
      "category": "certification",
      "by": {
        "@type": "Organization",
        "name": "Florida Realtors"
      }
    },
    {
      "name": "Bachelor of Science in Economics",
      "category": "degree",
      "by": {
        "@type": "CollegeOrUniversity",
        "name": "University of Tampa"
      },
      "shortName": "B.S. in Economics"
    },
    {
      "name": "Bachelor of Arts in International Affairs",
      "category": "degree",
      "by": {
        "@type": "CollegeOrUniversity",
        "name": "University of Tampa"
      },
      "shortName": "B.A. in International Affairs"
    },
    {
      "name": "FAA Part 107 Certified Drone Pilot",
      "category": "certification",
      "by": {
        "@type": "GovernmentOrganization",
        "name": "Federal Aviation Administration",
        "url": "https://www.faa.gov/"
      },
      "shortName": "Part 107 Certified Drone Pilot"
    }
  ],
  "brokerage": {
    "name": "Levin Rinke Realty",
    "url": "https://www.levinrinkerealty.com/"
  },
  "telephone": "+1-850-266-5005",
  "phoneDisplay": "(850) 266-5005",
  "email": "greggcostin@gmail.com",
  "contactHours": {
    "label": "6 a.m. to midnight Central, daily",
    "opens": "06:00",
    "closes": "00:00",
    "timeZone": "America/Chicago",
    "days": [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday"
    ]
  },
  "businessProfileHours": [
    {
      "@type": "OpeningHoursSpecification",
      "dayOfWeek": [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday"
      ],
      "opens": "00:00",
      "closes": "23:59"
    }
  ],
  "address": {
    "streetAddress": "220 W Garden St, Suite 125",
    "addressLocality": "Pensacola",
    "addressRegion": "FL",
    "postalCode": "32502",
    "addressCountry": "US"
  },
  "addressLine": "220 W Garden St, Suite 125, Pensacola, FL 32502",
  "licenses": [
    {
      "name": "Florida Real Estate Sales Associate License",
      "identifier": "SL3630964",
      "state": "Florida",
      "url": "https://www.myfloridalicense.com/portalsearches/VerifyLicensee/LicenseDetail?ID=AC5740A2FFB1E506A82D86E377ACE3EB",
      "statusAsOfCheck": "Current, Active",
      "checkedOn": "2026-09-07",
      "expiresOn": "2026-09-30"
    },
    {
      "name": "Alabama Real Estate Salesperson License",
      "identifier": "000171694-0",
      "state": "Alabama",
      "url": "https://arec.alabama.gov/apps/LicenseSearch/Home/Details/163221",
      "statusAsOfCheck": "Active",
      "checkedOn": "2026-09-07",
      "expiresOn": "2028-09-30"
    }
  ],
  "areasServed": [
    {
      "@type": "City",
      "name": "Pensacola"
    },
    {
      "@type": "City",
      "name": "Gulf Breeze"
    },
    {
      "@type": "City",
      "name": "Pace"
    },
    {
      "@type": "City",
      "name": "Milton"
    },
    {
      "@type": "City",
      "name": "Navarre"
    },
    {
      "@type": "City",
      "name": "Cantonment"
    },
    {
      "@type": "City",
      "name": "Perdido Key"
    },
    {
      "@type": "City",
      "name": "Niceville"
    },
    {
      "@type": "City",
      "name": "Fort Walton Beach"
    },
    {
      "@type": "City",
      "name": "Crestview"
    },
    {
      "@type": "City",
      "name": "Destin"
    },
    {
      "@type": "City",
      "name": "Orange Beach"
    },
    {
      "@type": "City",
      "name": "Gulf Shores"
    },
    {
      "@type": "City",
      "name": "Foley"
    },
    {
      "@type": "AdministrativeArea",
      "name": "Escambia County, FL"
    },
    {
      "@type": "AdministrativeArea",
      "name": "Santa Rosa County, FL"
    },
    {
      "@type": "AdministrativeArea",
      "name": "Okaloosa County, FL"
    },
    {
      "@type": "AdministrativeArea",
      "name": "Baldwin County, AL"
    }
  ],
  "profiles": [
    "https://pensacolamilitaryhousing.com/about",
    "https://www.google.com/maps/place/Gregg+Costin+Pensacola+Realtor+-+Levin+Rinke+Realty/@30.4129639,-87.2188735,17z/data=!4m6!3m5!1s0x8890c1a04a17d29b:0xaaa3b223c50fa5fc!8m2!3d30.4129639!4d-87.2188735!16s%2Fg%2F11mdg2zjxd",
    "https://www.zillow.com/profile/GreggCostin",
    "https://www.homes.com/real-estate-agents/gregg-costin/864f0f3/",
    "https://www.realtor.com/realestateagents/Gregg-Costin_Pensacola_FL_100641985_465184627",
    "https://www.linkedin.com/in/greggcostin",
    "https://baldwinrealtors.com/agents/gregg-costin",
    "https://www.facebook.com/greggcostin/",
    "https://www.instagram.com/greggcostinrealtor/",
    "https://linktr.ee/Greggcostin",
    "https://greggc.levinrinkerealty.com",
    "https://pensacolamls.com/members/gregg-costin/29891023"
  ],
  "websites": [
    {
      "name": "The Costin Team",
      "url": "https://greggcostin.com/",
      "profile": "https://greggcostin.com/team"
    },
    {
      "name": "Pensacola Military Housing",
      "url": "https://pensacolamilitaryhousing.com/",
      "profile": "https://pensacolamilitaryhousing.com/about"
    }
  ],
  "contactSource": {
    "url": "https://greggc.levinrinkerealty.com/",
    "checkedOn": "2026-09-07"
  },
  "recordUrl": "https://greggcostin.com/data/gregg-costin.json"
};
